// Visually reviewed classics; dates are not represented as current posts.
export const handpickedMedia = [
  {
    "id": "pinterest-jerry-quarter-reactions",
    "type": "meme",
    "origin": "community",
    "title": "Four quarters of Jerry",
    "caption": "DALLAS COWBOYS FANS BE LIKE... FIRST QUARTER; SECOND QUARTER; THIRD QUARTER; FOURTH QUARTER",
    "src": "./assets/handpicked/pinterest-jerry-quarter-reactions.jpg",
    "preview": "./assets/handpicked/pinterest-jerry-quarter-reactions.jpg",
    "sourceUrl": "https://www.pinterest.com/pin/jerry-jones-and-how-he-feels-losing-to-the-packers-lo--145804106660201766/",
    "sourceName": "Pinterest",
    "category": "Jerry’s World",
    "subject": "Jerry Jones",
    "tags": [
      "Jerry Jones",
      "Dallas Cowboys",
      "Game day",
      "Collapse",
      "Expectations vs reality"
    ],
    "width": 896,
    "height": 960,
    "qualityReason": "Four different photos build a readable arc from confidence to applause, agitation, and defeat. The sequence supplies the joke instead of a single generic smiling portrait.",
    "curated": true,
    "featuredRank": 3,
    "addedAt": "2026-09-28T14:41:08.937Z",
    "originalSrc": "https://i.pinimg.com/originals/77/73/3f/77733f2459183bdeb41dcdf8cc794511.jpg",
    "bestRoast": true,
    "classic": true
  },
  {
    "id": "imgflip-aims08",
    "type": "meme",
    "origin": "community",
    "title": "Mirror, mirror, same promise",
    "caption": "Dak says this is our year three times; the mirror reflects a trash can.",
    "src": "./assets/handpicked/imgflip-aims08.jpg",
    "preview": "./assets/handpicked/imgflip-aims08.jpg",
    "sourceUrl": "https://imgflip.com/i/aims08",
    "sourceName": "Imgflip",
    "category": "This is our year",
    "subject": "Dak Prescott",
    "tags": [
      "mirror",
      "trash can",
      "this is our year"
    ],
    "width": 595,
    "height": 500,
    "qualityReason": "A full visual transformation supplies the payoff; bold type stays readable.",
    "author": "TrustiGoat",
    "curated": true,
    "featuredRank": 1,
    "addedAt": "2026-09-28T14:41:08.938Z",
    "originalSrc": "https://i.imgflip.com/aims08.jpg"
  },
  {
    "id": "lola-jerry-maher-kicker",
    "type": "meme",
    "origin": "community",
    "title": "Jerry names himself the kicker",
    "caption": "Jerry Jones is photoshopped into a Cowboys uniform after Brett Maher misses another extra point.",
    "src": "./assets/handpicked/lola-jerry-maher-kicker.jpg",
    "preview": "./assets/handpicked/lola-jerry-maher-kicker.jpg",
    "sourceUrl": "https://lolalambchops.com/best-dallas-cowboys-losing-memes/",
    "sourceName": "Lola Lambchops",
    "category": "Jerry’s World",
    "subject": "Jerry Jones",
    "tags": [
      "Brett Maher",
      "extra point",
      "kicker",
      "playoffs"
    ],
    "width": 986,
    "height": 1024,
    "qualityReason": "The absurd uniform composite gives a specific joke about Jerry taking over after the kicking woes.",
    "author": "NFL Memes (@NFL_Memes), as credited in the image",
    "curated": true,
    "featuredRank": 2,
    "addedAt": "2026-09-28T14:41:08.938Z",
    "originalSrc": "https://lolalambchops.com/wp/wp-content/uploads/2023/01/Dallas-Cowboys-Playoff-loss-memes-986x1024.jpg"
  },
  {
    "id": "td-cowboys-20251212-14",
    "type": "meme",
    "origin": "community",
    "title": "Dak opens a bakery",
    "caption": "Dak serves a tray of pastries under the question: Turnovers anyone?",
    "src": "./assets/handpicked/td-cowboys-20251212-14.jpg",
    "preview": "./assets/handpicked/td-cowboys-20251212-14.jpg",
    "sourceUrl": "https://thunderdungeon.com/2025/12/13/20-dallas-cowboys-memes-for-fans-who-love-pain/",
    "sourceName": "Thunder Dungeon",
    "category": "Game day",
    "subject": "Dak Prescott",
    "tags": [
      "turnovers",
      "interceptions",
      "bakery"
    ],
    "width": 600,
    "height": 739,
    "qualityReason": "The literal pastry gag is immediately understandable and tied directly to Dak.",
    "curated": true,
    "featuredRank": 1,
    "addedAt": "2026-09-28T14:41:08.938Z",
    "originalSrc": "https://b3666184.assetcdn.net/3666184/wp-content/uploads/2025/12/dallas-cowboys-memes-14-20251212.jpg?lossy=2&strip=1&webp=1",
    "bestRoast": true,
    "classic": true
  },
  {
    "id": "imgflip-9kpcwr",
    "type": "meme",
    "origin": "community",
    "title": "Jerry Jones every offseason",
    "caption": "SAY THE LINE JERRY; WE'RE GOING ALL IN",
    "src": "./assets/handpicked/imgflip-9kpcwr.jpg",
    "preview": "./assets/handpicked/imgflip-9kpcwr.jpg",
    "sourceUrl": "https://imgflip.com/i/9kpcwr",
    "sourceName": "Imgflip",
    "category": "Jerry’s World",
    "subject": "Jerry Jones",
    "tags": [
      "Jerry Jones",
      "Dallas Cowboys",
      "All in",
      "Offseason",
      "Simpsons"
    ],
    "width": 500,
    "height": 822,
    "qualityReason": "A three-panel Simpsons crowd demands the familiar promise, Jerry delivers it, and the crowd celebrates. The panel progression satirizes the repeating offseason cycle.",
    "author": "NFLDude2K8",
    "curated": true,
    "featuredRank": 4,
    "addedAt": "2026-09-28T14:41:08.938Z",
    "originalSrc": "https://i.imgflip.com/9kpcwr.jpg"
  },
  {
    "id": "td-cowboys-20251212-10",
    "type": "meme",
    "origin": "community",
    "title": "Obsolete since the nineties",
    "caption": "The Cowboys star joins floppy disks and old cameras in a collection of now-useless 1990s favorites.",
    "src": "./assets/handpicked/td-cowboys-20251212-10.jpg",
    "preview": "./assets/handpicked/td-cowboys-20251212-10.jpg",
    "sourceUrl": "https://thunderdungeon.com/2025/12/13/20-dallas-cowboys-memes-for-fans-who-love-pain/",
    "sourceName": "Thunder Dungeon",
    "category": "Offseason",
    "subject": "Dallas Cowboys",
    "tags": [
      "1990s",
      "nostalgia",
      "obsolete",
      "Super Bowl drought"
    ],
    "width": 600,
    "height": 610,
    "qualityReason": "The visual analogy lands instantly and targets the franchise living on old glory.",
    "curated": true,
    "featuredRank": 4,
    "addedAt": "2026-09-28T14:41:08.938Z",
    "originalSrc": "https://b3666184.assetcdn.net/3666184/wp-content/uploads/2025/12/dallas-cowboys-memes-10-20251212.jpg?lossy=2&strip=1&webp=1",
    "bestRoast": true,
    "classic": true
  },
  {
    "id": "td-cowboys-20251212-11",
    "type": "meme",
    "origin": "community",
    "title": "Suddenly everybody has your number",
    "caption": "Two birthday messages versus 47 messages when the Cowboys lose.",
    "src": "./assets/handpicked/td-cowboys-20251212-11.jpg",
    "preview": "./assets/handpicked/td-cowboys-20251212-11.jpg",
    "sourceUrl": "https://thunderdungeon.com/2025/12/13/20-dallas-cowboys-memes-for-fans-who-love-pain/",
    "sourceName": "Thunder Dungeon",
    "category": "Game day",
    "subject": "Dallas Cowboys",
    "tags": [
      "group chat",
      "fans",
      "loss",
      "birthday"
    ],
    "width": 600,
    "height": 604,
    "qualityReason": "A concise modern group-chat joke with strong contrast and almost no reading burden.",
    "curated": true,
    "featuredRank": 2,
    "addedAt": "2026-09-28T14:41:08.938Z",
    "originalSrc": "https://b3666184.assetcdn.net/3666184/wp-content/uploads/2025/12/dallas-cowboys-memes-11-20251212.jpg?lossy=2&strip=1&webp=1",
    "bestRoast": true,
    "classic": true
  },
  {
    "id": "td-cowboys-20251212-13",
    "type": "meme",
    "origin": "community",
    "title": "Geometry of elimination",
    "caption": "Pentagon. Hexagon. Octagon. Seasongon.",
    "src": "./assets/handpicked/td-cowboys-20251212-13.jpg",
    "preview": "./assets/handpicked/td-cowboys-20251212-13.jpg",
    "sourceUrl": "https://thunderdungeon.com/2025/12/13/20-dallas-cowboys-memes-for-fans-who-love-pain/",
    "sourceName": "Thunder Dungeon",
    "category": "Playoffs",
    "subject": "Dallas Cowboys",
    "tags": [
      "elimination",
      "wordplay",
      "season over"
    ],
    "width": 600,
    "height": 688,
    "qualityReason": "A sharp visual pun using the Cowboys star as the final shape; clean and readable.",
    "curated": true,
    "featuredRank": 5,
    "addedAt": "2026-09-28T14:41:08.938Z",
    "originalSrc": "https://b3666184.assetcdn.net/3666184/wp-content/uploads/2025/12/dallas-cowboys-memes-13-20251212.jpg?lossy=2&strip=1&webp=1",
    "bestRoast": true,
    "classic": true
  },
  {
    "id": "pinterest-jerry-april-fools",
    "type": "meme",
    "origin": "community",
    "title": "The retirement announcement",
    "caption": "I’M RETIRING!!!! APRIL FOOLS!!",
    "src": "./assets/handpicked/pinterest-jerry-april-fools.jpg",
    "preview": "./assets/handpicked/pinterest-jerry-april-fools.jpg",
    "sourceUrl": "https://www.pinterest.com/pin/161496336626176247/",
    "sourceName": "Pinterest",
    "category": "Jerry’s World",
    "subject": "Jerry Jones",
    "tags": [
      "Jerry Jones",
      "Dallas Cowboys",
      "Retirement",
      "April Fools",
      "Front office"
    ],
    "width": 735,
    "height": 726,
    "qualityReason": "The apparent retirement announcement and immediate retraction are a complete two-beat joke about fans being unable to escape the same front office.",
    "curated": true,
    "featuredRank": 8,
    "addedAt": "2026-09-28T14:41:08.938Z",
    "originalSrc": "https://i.pinimg.com/736x/a4/02/c1/a402c11a2546763cc6525290893d4a8d.jpg"
  },
  {
    "id": "td-cowboys-20251212-19",
    "type": "meme",
    "origin": "community",
    "title": "Forced to watch the fourth quarter",
    "caption": "Security escorts a fan beneath a joke claiming Cowboys fans are being forced to watch until the end.",
    "src": "./assets/handpicked/td-cowboys-20251212-19.jpg",
    "preview": "./assets/handpicked/td-cowboys-20251212-19.jpg",
    "sourceUrl": "https://thunderdungeon.com/2025/12/13/20-dallas-cowboys-memes-for-fans-who-love-pain/",
    "sourceName": "Thunder Dungeon",
    "category": "Game day",
    "subject": "Dallas Cowboys",
    "tags": [
      "fans",
      "security",
      "loss",
      "fourth quarter"
    ],
    "width": 600,
    "height": 557,
    "qualityReason": "The caption reverses the apparent action in the photo for a sharp, specific suffering-through-a-loss joke.",
    "curated": true,
    "featuredRank": 0,
    "addedAt": "2026-09-28T14:41:08.938Z",
    "originalSrc": "https://b3666184.assetcdn.net/3666184/wp-content/uploads/2025/12/dallas-cowboys-memes-19-20251212.jpg?lossy=2&strip=1&webp=1",
    "bestRoast": true,
    "classic": true
  },
  {
    "id": "jerry-bum-steer",
    "type": "meme",
    "origin": "community",
    "title": "A trophy Jerry can actually win",
    "caption": "BUM STEER 2024",
    "src": "./assets/handpicked/jerry-bum-steer.jpg",
    "preview": "./assets/handpicked/jerry-bum-steer.jpg",
    "sourceUrl": "https://athlonsports.com/nfl/dallas-cowboys/dallas-cowboys-jerry-jones-texas-monthly-bum-steer-award-raccoon-eat-highest-dishonor-award",
    "sourceName": "Athlon Sports / Texas Monthly",
    "category": "Jerry’s World",
    "subject": "Jerry Jones",
    "tags": [
      "Jerry Jones",
      "Dallas Cowboys",
      "Trophy",
      "Satire",
      "2024"
    ],
    "width": 1536,
    "height": 960,
    "qualityReason": "A detailed satirical illustration stages an elaborate Cowboys trophy celebration for the Bum Steer dishonor. The trophy itself reverses the expectation of a championship celebration.",
    "curated": true,
    "featuredRank": 10,
    "addedAt": "2026-09-28T14:41:08.938Z",
    "originalSrc": "https://athlonsports.com/.image/ar_1.91%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cg_faces%3Acenter%2Cq_auto%3Agood%2Cw_1200/MjExNDc1MzY5MTM0NDAwNjcx/cowboys---jerry-bum-steer.jpg"
  },
  {
    "id": "td-cowboys-20251212-16",
    "type": "meme",
    "origin": "community",
    "title": "The only postgame celebration",
    "caption": "A stadium sign says a Cowboys fan celebrates a Super Bowl win by turning off the Xbox.",
    "src": "./assets/handpicked/td-cowboys-20251212-16.jpg",
    "preview": "./assets/handpicked/td-cowboys-20251212-16.jpg",
    "sourceUrl": "https://thunderdungeon.com/2025/12/13/20-dallas-cowboys-memes-for-fans-who-love-pain/",
    "sourceName": "Thunder Dungeon",
    "category": "Delusion",
    "subject": "Dallas Cowboys",
    "tags": [
      "Xbox",
      "Super Bowl",
      "stadium sign",
      "fans"
    ],
    "width": 600,
    "height": 550,
    "qualityReason": "A real readable fan sign gives the simulated-Super-Bowl punchline a different format and clear payoff.",
    "curated": true,
    "featuredRank": 11,
    "addedAt": "2026-09-28T14:41:08.938Z",
    "originalSrc": "https://b3666184.assetcdn.net/3666184/wp-content/uploads/2025/12/dallas-cowboys-memes-16-20251212.jpg?lossy=2&strip=1&webp=1"
  },
  {
    "id": "imgflip-26xql1",
    "type": "gif",
    "origin": "community",
    "title": "Cowboys Fans During Free Agency",
    "caption": "JOOOOOOOOONES!!!!!!!",
    "src": "./assets/handpicked/imgflip-26xql1.gif",
    "preview": "./assets/handpicked/imgflip-26xql1.gif",
    "sourceUrl": "https://imgflip.com/gif/26xql1",
    "sourceName": "Imgflip",
    "category": "Jerry’s World",
    "subject": "Jerry Jones",
    "tags": [
      "Jerry Jones",
      "Dallas Cowboys",
      "Free agency",
      "Frustration",
      "Star Trek"
    ],
    "width": 260,
    "height": 260,
    "qualityReason": "The full animated Kirk scream is retargeted at Jones; a clean, exaggerated fan reaction to an empty free-agency window, with a different visual vocabulary from the catalog’s Jerry interview and suite loops.",
    "poster": "./assets/handpicked/imgflip-26xql1.gif",
    "author": "MicahRobertson1",
    "curated": true,
    "featuredRank": 12,
    "addedAt": "2026-09-28T14:41:08.938Z",
    "originalSrc": "https://i.imgflip.com/26xql1.gif"
  },
  {
    "id": "pinterest-jerry-three-teams",
    "type": "meme",
    "origin": "community",
    "title": "Three teams ahead of you, Jerry",
    "caption": "WE HAVE A GOOD SHOT AT GETTING TO THE PLAYOFFS. WHY NOT US? THREE TEAMS AHEAD OF YOU JERRY!",
    "src": "./assets/handpicked/pinterest-jerry-three-teams.jpg",
    "preview": "./assets/handpicked/pinterest-jerry-three-teams.jpg",
    "sourceUrl": "https://www.pinterest.com/pin/jerry-jones-sucks--316237205066524284/",
    "sourceName": "Pinterest",
    "category": "Jerry’s World",
    "subject": "Jerry Jones",
    "tags": [
      "Jerry Jones",
      "Dallas Cowboys",
      "Playoffs",
      "Optimism",
      "Reality check"
    ],
    "width": 532,
    "height": 720,
    "qualityReason": "Jerry’s optimistic press conference is answered by the emphatic telephone scene from Planes, Trains and Automobiles. The visual exchange gives the standings joke a second character and a punchline.",
    "curated": true,
    "featuredRank": 13,
    "addedAt": "2026-09-28T14:41:08.938Z",
    "originalSrc": "https://i.pinimg.com/564x/2c/91/f8/2c91f883565d8f191b77c92caff07f96.jpg"
  },
  {
    "id": "td-cowboys-20251212-1",
    "type": "meme",
    "origin": "community",
    "title": "Same division, same story",
    "caption": "An NFC East comparison ends with Romo and Dak labeled regular-season merchants.",
    "src": "./assets/handpicked/td-cowboys-20251212-1.jpg",
    "preview": "./assets/handpicked/td-cowboys-20251212-1.jpg",
    "sourceUrl": "https://thunderdungeon.com/2025/12/13/20-dallas-cowboys-memes-for-fans-who-love-pain/",
    "sourceName": "Thunder Dungeon",
    "category": "Playoffs",
    "subject": "Dak Prescott, Tony Romo",
    "tags": [
      "regular season",
      "playoffs",
      "NFC East",
      "Tony Romo",
      "Dak Prescott"
    ],
    "width": 600,
    "height": 750,
    "qualityReason": "A clear four-part setup saves the Cowboys roast for the final row; specific to their postseason pattern.",
    "curated": true,
    "featuredRank": 14,
    "addedAt": "2026-09-28T14:41:08.938Z",
    "originalSrc": "https://b3666184.assetcdn.net/3666184/wp-content/uploads/2025/12/dallas-cowboys-memes-1-20251212.jpg?lossy=2&strip=1&webp=1"
  },
  {
    "id": "td-cowboys-20251212-3",
    "type": "meme",
    "origin": "community",
    "title": "The early interception fork",
    "caption": "An early Dak interception opens two paths: Hall of Fame quarterback play or the worst game ever.",
    "src": "./assets/handpicked/td-cowboys-20251212-3.jpg",
    "preview": "./assets/handpicked/td-cowboys-20251212-3.jpg",
    "sourceUrl": "https://thunderdungeon.com/2025/12/13/20-dallas-cowboys-memes-for-fans-who-love-pain/",
    "sourceName": "Thunder Dungeon",
    "category": "Game day",
    "subject": "Dak Prescott",
    "tags": [
      "interceptions",
      "quarterback",
      "inconsistency"
    ],
    "width": 600,
    "height": 600,
    "qualityReason": "A readable two-path visual captures the peculiar uncertainty of watching Dak after an early pick.",
    "curated": true,
    "featuredRank": 15,
    "addedAt": "2026-09-28T14:41:08.939Z",
    "originalSrc": "https://b3666184.assetcdn.net/3666184/wp-content/uploads/2025/12/dallas-cowboys-memes-3-20251212.jpg?lossy=2&strip=1&webp=1"
  },
  {
    "id": "td-cowboys-20251212-4",
    "type": "meme",
    "origin": "community",
    "title": "More believable than a Dallas Super Bowl",
    "caption": "Bigfoot riding the Loch Ness Monster is more believable than the Cowboys going to the Super Bowl.",
    "src": "./assets/handpicked/td-cowboys-20251212-4.jpg",
    "preview": "./assets/handpicked/td-cowboys-20251212-4.jpg",
    "sourceUrl": "https://thunderdungeon.com/2025/12/13/20-dallas-cowboys-memes-for-fans-who-love-pain/",
    "sourceName": "Thunder Dungeon",
    "category": "Delusion",
    "subject": "Dallas Cowboys",
    "tags": [
      "Super Bowl",
      "Bigfoot",
      "Loch Ness",
      "delusion"
    ],
    "width": 600,
    "height": 571,
    "qualityReason": "An absurd composite delivers one immediate Cowboys-specific punchline; no filler reaction image.",
    "curated": true,
    "featuredRank": 16,
    "addedAt": "2026-09-28T14:41:08.939Z",
    "originalSrc": "https://b3666184.assetcdn.net/3666184/wp-content/uploads/2025/12/dallas-cowboys-memes-4-20251212.jpg?lossy=2&strip=1&webp=1"
  },
  {
    "id": "td-cowboys-20251212-8",
    "type": "meme",
    "origin": "community",
    "title": "The seasonal wardrobe change",
    "caption": "After playoff elimination, Homer retreats in a Cowboys jersey and returns in Lakers and Yankees gear.",
    "src": "./assets/handpicked/td-cowboys-20251212-8.jpg",
    "preview": "./assets/handpicked/td-cowboys-20251212-8.jpg",
    "sourceUrl": "https://thunderdungeon.com/2025/12/13/20-dallas-cowboys-memes-for-fans-who-love-pain/",
    "sourceName": "Thunder Dungeon",
    "category": "Playoffs",
    "subject": "Dallas Cowboys",
    "tags": [
      "bandwagon",
      "fans",
      "Homer Simpson",
      "Lakers",
      "Yankees"
    ],
    "width": 600,
    "height": 752,
    "qualityReason": "A complete four-panel visual joke about bandwagon fandom, with the team logos carrying the punchline.",
    "curated": true,
    "featuredRank": 17,
    "addedAt": "2026-09-28T14:41:08.939Z",
    "originalSrc": "https://b3666184.assetcdn.net/3666184/wp-content/uploads/2025/12/dallas-cowboys-memes-8-20251212.jpg?lossy=2&strip=1&webp=1"
  },
  {
    "id": "td-cowboys-20251212-15",
    "type": "meme",
    "origin": "community",
    "title": "The VCR consolation plan",
    "caption": "A Cowboys fan is consoled with an invitation to watch the Super Bowl on the VCR.",
    "src": "./assets/handpicked/td-cowboys-20251212-15.jpg",
    "preview": "./assets/handpicked/td-cowboys-20251212-15.jpg",
    "sourceUrl": "https://thunderdungeon.com/2025/12/13/20-dallas-cowboys-memes-for-fans-who-love-pain/",
    "sourceName": "Thunder Dungeon",
    "category": "Playoffs",
    "subject": "Dallas Cowboys",
    "tags": [
      "VCR",
      "1990s",
      "nostalgia",
      "fans"
    ],
    "width": 600,
    "height": 511,
    "qualityReason": "A specific visual consolation joke gives the old-glory theme more personality than a generic VHS statement.",
    "curated": true,
    "featuredRank": 18,
    "addedAt": "2026-09-28T14:41:08.939Z",
    "originalSrc": "https://b3666184.assetcdn.net/3666184/wp-content/uploads/2025/12/dallas-cowboys-memes-15-20251212.jpg?lossy=2&strip=1&webp=1"
  },
  {
    "id": "td-cowboys-20251212-18",
    "type": "meme",
    "origin": "community",
    "title": "Believing in impossible things",
    "caption": "The meme defends children who believe in Santa by pointing to grown-ups who believe in the Cowboys.",
    "src": "./assets/handpicked/td-cowboys-20251212-18.jpg",
    "preview": "./assets/handpicked/td-cowboys-20251212-18.jpg",
    "sourceUrl": "https://thunderdungeon.com/2025/12/13/20-dallas-cowboys-memes-for-fans-who-love-pain/",
    "sourceName": "Thunder Dungeon",
    "category": "Delusion",
    "subject": "Dallas Cowboys",
    "tags": [
      "Santa",
      "Christmas",
      "adult fans",
      "belief"
    ],
    "width": 600,
    "height": 761,
    "qualityReason": "The joke explicitly targets adult fan optimism; friendly imagery supports a clean roast.",
    "curated": true,
    "featuredRank": 19,
    "addedAt": "2026-09-28T14:41:08.939Z",
    "originalSrc": "https://b3666184.assetcdn.net/3666184/wp-content/uploads/2025/12/dallas-cowboys-memes-18-20251212.jpg?lossy=2&strip=1&webp=1"
  },
  {
    "id": "imgflip-7f8f7k",
    "type": "meme",
    "origin": "community",
    "title": "Say the line, Cowboys",
    "caption": "The Simpsons class prompts the Cowboys after signing Brandin Cooks: This is our year.",
    "src": "./assets/handpicked/imgflip-7f8f7k.jpg",
    "preview": "./assets/handpicked/imgflip-7f8f7k.jpg",
    "sourceUrl": "https://imgflip.com/i/7f8f7k",
    "sourceName": "Imgflip",
    "category": "This is our year",
    "subject": "Dallas Cowboys",
    "tags": [
      "Simpsons",
      "Brandin Cooks",
      "offseason hype",
      "this is our year"
    ],
    "width": 500,
    "height": 822,
    "qualityReason": "A recognizable three-panel ritual makes fun of fan optimism restarting after every signing. The original image misspells Brandin as Branding.",
    "author": "Mb15",
    "curated": true,
    "featuredRank": 20,
    "addedAt": "2026-09-28T14:41:08.939Z",
    "originalSrc": "https://i.imgflip.com/7f8f7k.jpg"
  },
  {
    "id": "imgflip-8cctb8",
    "type": "meme",
    "origin": "community",
    "title": "Superman until January",
    "caption": "Superman represents the regular season; the bumbling Greatest American Hero represents the playoffs.",
    "src": "./assets/handpicked/imgflip-8cctb8.jpg",
    "preview": "./assets/handpicked/imgflip-8cctb8.jpg",
    "sourceUrl": "https://imgflip.com/i/8cctb8",
    "sourceName": "Imgflip",
    "category": "Playoffs",
    "subject": "Dallas Cowboys",
    "tags": [
      "regular season",
      "Superman",
      "Greatest American Hero",
      "playoff collapse"
    ],
    "width": 500,
    "height": 1291,
    "qualityReason": "Two contrasting superhero images make the postseason collapse joke immediately visual.",
    "author": "kevro1977",
    "curated": true,
    "featuredRank": 21,
    "addedAt": "2026-09-28T14:41:08.939Z",
    "originalSrc": "https://i.imgflip.com/8cctb8.jpg"
  },
  {
    "id": "lola-woody-superbowl",
    "type": "meme",
    "origin": "community",
    "title": "Woody cannot explain the Super Bowl",
    "caption": "Buzz asks what a Super Bowl is. Woody does not know because he is a cowboy.",
    "src": "./assets/handpicked/lola-woody-superbowl.jpg",
    "preview": "./assets/handpicked/lola-woody-superbowl.jpg",
    "sourceUrl": "https://lolalambchops.com/best-dallas-cowboys-losing-memes/",
    "sourceName": "Lola Lambchops",
    "category": "Playoffs",
    "subject": "Dallas Cowboys",
    "tags": [
      "Toy Story",
      "Woody",
      "Buzz Lightyear",
      "Super Bowl drought"
    ],
    "width": 600,
    "height": 600,
    "qualityReason": "The familiar Toy Story characters give the cowboy wordplay a crisp two-line punchline.",
    "curated": true,
    "featuredRank": 22,
    "addedAt": "2026-09-28T14:41:08.939Z",
    "originalSrc": "https://lolalambchops.com/wp/wp-content/uploads/2023/01/Dallas-Cowboys-memes.jpg"
  },
  {
    "id": "imgflip-4k3ko5",
    "type": "meme",
    "origin": "community",
    "title": "Jerry Knows Best",
    "caption": "SORRY. NOT SORRY.",
    "src": "./assets/handpicked/imgflip-4k3ko5.jpg",
    "preview": "./assets/handpicked/imgflip-4k3ko5.jpg",
    "sourceUrl": "https://imgflip.com/i/4k3ko5",
    "sourceName": "Imgflip",
    "category": "Jerry’s World",
    "subject": "Jerry Jones",
    "tags": [
      "Jerry Jones",
      "Dallas Cowboys",
      "Press conference",
      "Accountability",
      "Radio"
    ],
    "width": 645,
    "height": 500,
    "qualityReason": "The mock royal apology pairs Mel Brooks’ king with the reported Jerry radio-host apology, turning a public-relations non-apology into the visual punchline.",
    "curated": true,
    "featuredRank": 23,
    "addedAt": "2026-09-28T14:41:08.939Z",
    "originalSrc": "https://i.imgflip.com/4k3ko5.jpg"
  },
  {
    "id": "dmn-jerry-cassel-player-week",
    "type": "meme",
    "origin": "community",
    "title": "The other team’s player of the week",
    "caption": "THE FACE YOU MAKE WHEN MATT CASSEL IS NAMED GIANTS PLAYER OF THE WEEK.",
    "src": "./assets/handpicked/dmn-jerry-cassel-player-week.jpg",
    "preview": "./assets/handpicked/dmn-jerry-cassel-player-week.jpg",
    "sourceUrl": "https://www.dallasnews.com/sports/cowboys/2015/10/28/the-best-memes-of-fans-mercilessly-making-fun-of-cowboys-jerry-jones/",
    "sourceName": "The Dallas Morning News",
    "category": "Jerry’s World",
    "subject": "Jerry Jones",
    "tags": [
      "Jerry Jones",
      "Dallas Cowboys",
      "Quarterback",
      "Interceptions",
      "Rivalry"
    ],
    "width": 830,
    "height": 436,
    "qualityReason": "A specific turnover punchline makes the Cowboys quarterback the rival Giants’ most valuable contributor. Jerry’s tight-lipped expression completes a joke that reads without additional context.",
    "curated": true,
    "featuredRank": 24,
    "addedAt": "2026-09-28T14:41:08.939Z",
    "originalSrc": "https://dmn-dallas-news-prod.cdn.arcpublishing.com/resizer/v2/B7VPRC6DCDWJS57DD4G2HJSEXI.jpg?auth=a79cb376129bdb1f7bfaa8916334981053f239518e734207d35e811d27659419&quality=80&width=830"
  }
];
