// Visually reviewed classics; dates are not represented as current posts.
export const handpickedMedia = [
  {
    "id": "x-1961188212510265567",
    "title": "The NFC East’s favorite general manager",
    "caption": "The NFC East to Jerry Jones every year: “Carefully, he’s a hero.”",
    "sourceUrl": "https://x.com/NFLMemes/status/1961188212510265567",
    "author": "@NFLMemes",
    "credit": "Published by @NFLMemes on X; original visual creator not independently established",
    "sourcePostDate": "2025-08-28T22:04:41Z",
    "classic": true,
    "type": "meme",
    "category": "Jerry’s World",
    "subject": "Jerry Jones",
    "tags": [
      "Jerry Jones",
      "NFC East",
      "Giants",
      "Eagles",
      "Commanders",
      "front office",
      "Spider-Man",
      "classic"
    ],
    "originalSrc": "https://pbs.twimg.com/media/GzeKSJrWgAAYnUJ.jpg?name=orig",
    "width": 1200,
    "height": 1319,
    "sha256": "9aea5954f360a7b7e66ec9d0551cd8c00d86ad9d7bb3f4214ee853312baa095e",
    "qualityReason": "Strong immediate visual punchline: all three rivals celebrate the Cowboys owner/GM as their hero. Large logos and recognizable Jerry face work at phone size.",
    "contentNote": "Classic from August 2025. Edited Spider-Man scene; satirical composite, not an actual event.",
    "reviewedAt": "2026-09-28",
    "sourceName": "X",
    "cleanReview": "Actual full-resolution local asset inspected. No slurs, explicit profanity, politics, or sexual/death jokes in selected image.",
    "dateVerification": "Canonical X result date visually checked; exact UTC source timestamp preserved from public FxTwitter source metadata saved beside asset.",
    "bestRoast": true,
    "origin": "community",
    "curated": true,
    "addedAt": "2026-09-28T20:37:11.163Z",
    "src": "./assets/handpicked/x-1961188212510265567.jpg",
    "preview": "./assets/handpicked/x-1961188212510265567.jpg",
    "featuredRank": -243,
    "reviewed": true
  },
  {
    "id": "x-1767588477523100068",
    "title": "All-in: Cowboys signing nobody",
    "caption": "2024 offseason parody: Jerry says all-in; the Cowboys sign nobody.",
    "sourceUrl": "https://x.com/ghetto_gronk/status/1767588477523100068",
    "author": "@ghetto_gronk",
    "credit": "Published by @ghetto_gronk on X; original visual creator not independently established",
    "sourcePostDate": "2024-03-12T16:28:27Z",
    "classic": true,
    "type": "meme",
    "category": "Jerry’s World",
    "subject": "Jerry Jones",
    "tags": [
      "Jerry Jones",
      "all in",
      "free agency",
      "front office",
      "classic"
    ],
    "originalSrc": "https://pbs.twimg.com/media/GIe8WPgWgAUwtIC.jpg?name=orig",
    "width": 1924,
    "height": 2048,
    "sha256": "838a7dca7f5629480274614742f4fc01ccb39d24afab5471411284f90c831bb5",
    "qualityReason": "Clean, self-contained breaking-news parody with huge readable punchline. Directly mocks Jerry’s all-in promise rather than generic Dallas losing.",
    "contentNote": "Classic from March 2024. Parody news graphic about that offseason; not a current transaction report.",
    "reviewedAt": "2026-09-28",
    "sourceName": "X",
    "cleanReview": "Actual full-resolution local asset inspected. No slurs, explicit profanity, politics, or sexual/death jokes in selected image.",
    "dateVerification": "Canonical X result date visually checked; exact UTC source timestamp preserved from public FxTwitter source metadata saved beside asset.",
    "bestRoast": false,
    "origin": "community",
    "curated": true,
    "addedAt": "2026-09-28T20:37:11.163Z",
    "src": "./assets/handpicked/x-1767588477523100068.jpg",
    "preview": "./assets/handpicked/x-1767588477523100068.jpg",
    "featuredRank": -242,
    "reviewed": true
  },
  {
    "id": "x-1615185225239207937",
    "title": "Parody: Jerry opens kicker tryouts in the stands",
    "caption": "Parody tweet: Jerry has a jersey ready for any fan who can kick.",
    "sourceUrl": "https://x.com/NFLMemes/status/1615185225239207937",
    "author": "@NFLMemes",
    "credit": "Published by @NFLMemes on X; original visual creator not independently established",
    "sourcePostDate": "2023-01-17T03:12:21Z",
    "classic": true,
    "type": "meme",
    "category": "Jerry’s World",
    "subject": "Jerry Jones",
    "tags": [
      "Jerry Jones",
      "kicker",
      "parody",
      "front office",
      "classic"
    ],
    "originalSrc": "https://pbs.twimg.com/media/FmpKZrwXkAEN7Dy.jpg?name=orig",
    "width": 1200,
    "height": 804,
    "sha256": "d074c21c7a41eb7ac96d5a5e9dd9e70f3781d58568a3273b7dc07258ddf33a05",
    "qualityReason": "Readable mock emergency recruiting post. The owner/GM’s alleged plan is to draft a spectator mid-game; specific, immediate absurdity.",
    "contentNote": "Classic from January 2023. Fake/parody Jerry tweet published by @NFLMemes, not a genuine Jerry Jones post. Keep Parody visible in the title and caption, not only metadata.",
    "reviewedAt": "2026-09-28",
    "sourceName": "X",
    "cleanReview": "Actual full-resolution local asset inspected. No slurs, explicit profanity, politics, or sexual/death jokes in selected image.",
    "dateVerification": "Canonical X result date visually checked; exact UTC source timestamp preserved from public FxTwitter source metadata saved beside asset.",
    "bestRoast": false,
    "origin": "community",
    "curated": true,
    "addedAt": "2026-09-28T20:37:11.163Z",
    "src": "./assets/handpicked/x-1615185225239207937.jpg",
    "preview": "./assets/handpicked/x-1615185225239207937.jpg",
    "featuredRank": -241,
    "reviewed": true
  },
  {
    "id": "community-dak-impractical-final-play",
    "title": "The final play was an Impractical Jokers challenge",
    "author": "@NFL_Memes",
    "sourceUrl": "https://www.ebaumsworld.com/pictures/dont-worry-cowboys-fans-your-daughters-already-know-how-to-choke-20-defeated-dallas-memes/87339967/",
    "sourceName": "eBaum’s World / NFL Memes",
    "caption": "Alright Dak.. The Impractical Jokers tell Dak to run the play where Zeke snaps it, gets annihilated, and the pass goes only 10 yards.",
    "category": "Playoffs",
    "tags": [
      "dak prescott",
      "ezekiel elliott",
      "zeke at center",
      "49ers",
      "impractical jokers",
      "final play",
      "playoff loss"
    ],
    "qualityScore": 96,
    "qualityReason": "A specific disastrous Cowboys play becomes an Impractical Jokers dare; the setup, play, and laughing payoff are all preserved and readable.",
    "originalSrc": "https://cdn.ebaumsworld.com/2023/01/23/125036/87339979/IMG_9794.jpg",
    "classic": true,
    "reviewedAt": "2026-09-28",
    "cleanReview": "Pass: football/fan satire, no profanity, slurs, sexual content, or injury/death punchlines.",
    "sha256": "1ed7b324d3a9a9929988b00f169b8194124bc5de3739ae0c72e081023048cf31",
    "sourcePostDate": null,
    "classicDateUnknown": true,
    "originalCreationDate": null,
    "width": 1170,
    "height": 1797,
    "sourceArticleDate": null,
    "attributionNote": "Creator name/handle is visible in the preserved screenshot. Original social post URL and exact date unavailable. CDN path is not treated as verified post date.",
    "type": "meme",
    "contentNote": "Historical satire of the final Cowboys offensive play against San Francisco in the 2022-season divisional round, January 2023.",
    "dateVerification": "Creator name/handle is visible in the preserved screenshot. Original social post URL and exact date unavailable. CDN path is not treated as verified post date.",
    "bestRoast": true,
    "origin": "community",
    "curated": true,
    "addedAt": "2026-09-28T20:37:11.163Z",
    "src": "./assets/handpicked/community-dak-impractical-final-play.jpg",
    "preview": "./assets/handpicked/community-dak-impractical-final-play.jpg",
    "subject": "Dallas Cowboys",
    "featuredRank": -240,
    "reviewed": true
  },
  {
    "id": "community-att-conference-championship",
    "title": "Parody: Dallas finally gets a conference championship",
    "author": "@TheGhettoGronk",
    "sourceUrl": "https://www.ebaumsworld.com/pictures/dont-worry-cowboys-fans-your-daughters-already-know-how-to-choke-20-defeated-dallas-memes/87339967/",
    "sourceName": "eBaum’s World / GhettoGronk",
    "caption": "Satirical announcement: hold a neutral-site NFC Championship at AT&T Stadium so Dallas fans can finally experience a conference championship.",
    "category": "Jerry’s World",
    "tags": [
      "at&t stadium",
      "jerrys world",
      "nfc championship",
      "neutral site",
      "playoff drought",
      "ghettogronk"
    ],
    "qualityScore": 95,
    "qualityReason": "A sharp stadium-specific punchline with an actual AT&T Stadium photo. The fake-news format lands immediately.",
    "originalSrc": "https://cdn.ebaumsworld.com/2023/01/23/125037/87339980/IMG_9796.jpg",
    "classic": true,
    "reviewedAt": "2026-09-28",
    "cleanReview": "Pass: football/fan satire, no profanity, slurs, sexual content, or injury/death punchlines.",
    "sha256": "f24d7fbbda5439997fe0aac775bc48ed2038f2c587a6d37383f62a686f640e49",
    "sourcePostDate": null,
    "classicDateUnknown": true,
    "originalCreationDate": null,
    "width": 1170,
    "height": 1580,
    "sourceArticleDate": null,
    "attributionNote": "Creator name/handle is visible in the preserved screenshot. Original social post URL and exact date unavailable. CDN path is not treated as verified post date.",
    "type": "meme",
    "contentNote": "Satirical announcement, not an actual NFL decision. Older postseason-drought joke.",
    "dateVerification": "Creator name/handle is visible in the preserved screenshot. Original social post URL and exact date unavailable. CDN path is not treated as verified post date.",
    "bestRoast": true,
    "origin": "community",
    "curated": true,
    "addedAt": "2026-09-28T20:37:11.163Z",
    "src": "./assets/handpicked/community-att-conference-championship.jpg",
    "preview": "./assets/handpicked/community-att-conference-championship.jpg",
    "subject": "Dallas Cowboys",
    "featuredRank": -239,
    "reviewed": true
  },
  {
    "id": "community-superbowl-tickets",
    "title": "Not without tickets",
    "author": null,
    "sourceUrl": "https://www.digitalmomblog.com/dallas-cowboys-memes/",
    "sourceName": "Digital Mom Blog",
    "caption": "THE COWBOYS ARE GOING TO THE SUPERBOWL. NOT WITHOUT TICKETS.",
    "category": "Delusion",
    "tags": [
      "super bowl",
      "tickets",
      "woman yelling at cat",
      "this is our year",
      "fan delusion"
    ],
    "qualityScore": 93,
    "qualityReason": "A compact two-panel setup and punchline; the boast gets demolished in four words. Readable without historical context.",
    "originalSrc": "https://digitalmomblog.b-cdn.net/wp-content/uploads/2021/09/dallas-cowboy-superbowl-tickets-meme.jpeg",
    "classic": true,
    "reviewedAt": "2026-09-28",
    "cleanReview": "Pass: football/fan satire, no profanity, slurs, sexual content, or injury/death punchlines.",
    "sha256": "c0ac4ec1d4c1f899a464cdcfd6f6d14f73001feec701c3be9ce73676808ce005",
    "sourcePostDate": null,
    "classicDateUnknown": true,
    "originalCreationDate": null,
    "width": 700,
    "height": 367,
    "sourceArticleDate": "2025-05-27",
    "sourceArticleDateType": "last updated",
    "attributionNote": "Source is a compilation; its update date is not the original meme post date. Original creator not listed except where a visible watermark is recorded.",
    "type": "meme",
    "contentNote": "Timeless Cowboys Super Bowl boast joke; original creator and date not listed by source.",
    "dateVerification": "Source is a compilation; its update date is not the original meme post date. Original creator not listed except where a visible watermark is recorded.",
    "bestRoast": false,
    "origin": "community",
    "curated": true,
    "addedAt": "2026-09-28T20:37:11.163Z",
    "src": "./assets/handpicked/community-superbowl-tickets.jpg",
    "preview": "./assets/handpicked/community-superbowl-tickets.jpg",
    "subject": "Dallas Cowboys",
    "featuredRank": -238,
    "reviewed": true
  },
  {
    "id": "community-literal-cowboys-fan",
    "title": "The most accurate Cowboys fan",
    "author": "NFL_MEMES (visible watermark)",
    "sourceUrl": "https://www.digitalmomblog.com/dallas-cowboys-memes/",
    "sourceName": "Digital Mom Blog / NFL Memes",
    "caption": "DALLAS COWBOYS FAN. LOUD, OBNOXIOUS AND MOSTLY BLOWS HOT AIR.",
    "category": "Delusion",
    "tags": [
      "cowboys fans",
      "hot air",
      "ceiling fan",
      "fan delusion",
      "nfl memes"
    ],
    "qualityScore": 91,
    "qualityReason": "A Cowboys-branded ceiling fan makes the insult literal, with an immediate visual punchline. Original watermark preserved.",
    "originalSrc": "https://digitalmomblog.b-cdn.net/wp-content/uploads/2021/09/dallas-cowboy-fan-loud-meme.jpeg",
    "classic": true,
    "reviewedAt": "2026-09-28",
    "cleanReview": "Pass: football/fan satire, no profanity, slurs, sexual content, or injury/death punchlines.",
    "sha256": "a8d8293b120d60aacbb012ca668bf031105aeaf83ed6731f528c3be7ead8feef",
    "sourcePostDate": null,
    "classicDateUnknown": true,
    "originalCreationDate": null,
    "width": 474,
    "height": 353,
    "sourceArticleDate": "2025-05-27",
    "sourceArticleDateType": "last updated",
    "attributionNote": "Source is a compilation; its update date is not the original meme post date. Original creator not listed except where a visible watermark is recorded.",
    "type": "meme",
    "contentNote": "Timeless wordplay; original post date unknown.",
    "dateVerification": "Source is a compilation; its update date is not the original meme post date. Original creator not listed except where a visible watermark is recorded.",
    "bestRoast": false,
    "origin": "community",
    "curated": true,
    "addedAt": "2026-09-28T20:37:11.163Z",
    "src": "./assets/handpicked/community-literal-cowboys-fan.jpg",
    "preview": "./assets/handpicked/community-literal-cowboys-fan.jpg",
    "subject": "Dallas Cowboys",
    "featuredRank": -237,
    "reviewed": true
  },
  {
    "id": "community-better-gift-than-jersey",
    "title": "Still a better gift",
    "author": null,
    "sourceUrl": "https://www.digitalmomblog.com/dallas-cowboys-memes/",
    "sourceName": "Digital Mom Blog",
    "caption": "STILL A BETTER GIFT THAN A COWBOYS JERSEY.",
    "category": "Cowboys",
    "tags": [
      "cowboys jersey",
      "christmas",
      "a christmas story",
      "ralphie",
      "pink bunny suit",
      "gifts"
    ],
    "qualityScore": 89,
    "qualityReason": "The humiliating pink bunny suit from A Christmas Story is still preferable to Cowboys merchandise. Simple and clean, with fully readable text.",
    "originalSrc": "https://digitalmomblog.b-cdn.net/wp-content/uploads/2021/09/still-a-better-gift-than-cowboys-jersey-meme.jpeg",
    "classic": true,
    "reviewedAt": "2026-09-28",
    "cleanReview": "Pass: football/fan satire, no profanity, slurs, sexual content, or injury/death punchlines.",
    "sha256": "b554e33b2d9b71467fc00b587fbf5ac6a2caafc49dc3dab697eef20c3380df60",
    "sourcePostDate": null,
    "classicDateUnknown": true,
    "originalCreationDate": null,
    "width": 382,
    "height": 519,
    "sourceArticleDate": "2025-05-27",
    "sourceArticleDateType": "last updated",
    "attributionNote": "Source is a compilation; its update date is not the original meme post date. Original creator not listed except where a visible watermark is recorded.",
    "type": "meme",
    "contentNote": "Classic film-image joke. Small original image (382×519), but the full punchline is legible.",
    "dateVerification": "Source is a compilation; its update date is not the original meme post date. Original creator not listed except where a visible watermark is recorded.",
    "bestRoast": false,
    "origin": "community",
    "curated": true,
    "addedAt": "2026-09-28T20:37:11.163Z",
    "src": "./assets/handpicked/community-better-gift-than-jersey.jpg",
    "preview": "./assets/handpicked/community-better-gift-than-jersey.jpg",
    "subject": "Dallas Cowboys",
    "featuredRank": -236,
    "reviewed": true
  },
  {
    "id": "community-romo-dak-same-team",
    "title": "Different quarterback. Same Cowboys.",
    "author": "@WhatGoingDowney",
    "sourceUrl": "https://www.ebaumsworld.com/pictures/dont-worry-cowboys-fans-your-daughters-already-know-how-to-choke-20-defeated-dallas-memes/87339967/",
    "sourceName": "eBaum’s World / Tom Downey",
    "caption": "Hard to swallow pills: THE ROMO COWBOYS AND THE DAK COWBOYS ARE THE SAME TEAM.",
    "category": "Playoffs",
    "tags": [
      "tony romo",
      "dak prescott",
      "hard to swallow pills",
      "same team",
      "playoff failure"
    ],
    "qualityScore": 89,
    "qualityReason": "A specific multi-era Cowboys comparison, with the original post’s emotional setup and hard-to-swallow-pills payoff preserved.",
    "originalSrc": "https://cdn.ebaumsworld.com/2023/01/23/125006/87339973/IMG_9790.jpg",
    "classic": true,
    "reviewedAt": "2026-09-28",
    "cleanReview": "Pass: football/fan satire, no profanity, slurs, sexual content, or injury/death punchlines.",
    "sha256": "5e5802c11f3215d802ff88aa41ee1dee462318262ca832877461caec6185ecd4",
    "sourcePostDate": null,
    "classicDateUnknown": true,
    "originalCreationDate": null,
    "width": 1170,
    "height": 1659,
    "sourceArticleDate": null,
    "attributionNote": "Creator name/handle is visible in the preserved screenshot. Original social post URL and exact date unavailable. CDN path is not treated as verified post date.",
    "type": "meme",
    "contentNote": "Historical reaction to a January 2023 playoff elimination; original post date unavailable.",
    "dateVerification": "Creator name/handle is visible in the preserved screenshot. Original social post URL and exact date unavailable. CDN path is not treated as verified post date.",
    "bestRoast": false,
    "origin": "community",
    "curated": true,
    "addedAt": "2026-09-28T20:37:11.163Z",
    "src": "./assets/handpicked/community-romo-dak-same-team.jpg",
    "preview": "./assets/handpicked/community-romo-dak-same-team.jpg",
    "subject": "Dallas Cowboys",
    "featuredRank": -235,
    "reviewed": true
  },
  {
    "id": "community-dak-sleep-number",
    "title": "Dak when Dallas needs him most",
    "author": "@FunGuyBurner",
    "sourceUrl": "https://www.ebaumsworld.com/pictures/dont-worry-cowboys-fans-your-daughters-already-know-how-to-choke-20-defeated-dallas-memes/87339967/",
    "sourceName": "eBaum’s World / Fun Guy",
    "caption": "Dak Prescott when the Cowboys need him most against the 49ers: his Sleep Number commercial.",
    "category": "Playoffs",
    "tags": [
      "dak prescott",
      "sleep number",
      "49ers",
      "asleep",
      "playoff performance"
    ],
    "qualityScore": 88,
    "qualityReason": "Uses Dak’s own sleeping advertisement against his playoff performance. The original text supplies a real Cowboys-specific joke.",
    "originalSrc": "https://cdn.ebaumsworld.com/2023/01/23/125034/87339978/IMG_9795.jpg",
    "classic": true,
    "reviewedAt": "2026-09-28",
    "cleanReview": "Pass: football/fan satire, no profanity, slurs, sexual content, or injury/death punchlines.",
    "sha256": "1a9737e3d9db0a682c638c5965bf31cfb00b5517da74d5994bcccb7208fe3b30",
    "sourcePostDate": null,
    "classicDateUnknown": true,
    "originalCreationDate": null,
    "width": 1170,
    "height": 1231,
    "sourceArticleDate": null,
    "attributionNote": "Creator name/handle is visible in the preserved screenshot. Original social post URL and exact date unavailable. CDN path is not treated as verified post date.",
    "type": "meme",
    "contentNote": "Older Dallas–San Francisco playoff joke. Catalog has a raw Sleep Number reaction GIF; this is a distinct captioned screenshot, not that same asset.",
    "dateVerification": "Creator name/handle is visible in the preserved screenshot. Original social post URL and exact date unavailable. CDN path is not treated as verified post date.",
    "bestRoast": false,
    "origin": "community",
    "curated": true,
    "addedAt": "2026-09-28T20:37:11.163Z",
    "src": "./assets/handpicked/community-dak-sleep-number.jpg",
    "preview": "./assets/handpicked/community-dak-sleep-number.jpg",
    "subject": "Dallas Cowboys",
    "featuredRank": -234,
    "reviewed": true
  },
  {
    "id": "community-same-excuses-2015",
    "title": "The same excuses, every year",
    "author": null,
    "sourceUrl": "https://www.chron.com/sports/texans/article/Check-out-the-best-NFL-memes-from-Week-3-6533864.php",
    "sourceName": "Chron",
    "caption": "You know what’s cool about Dallas? Every year they lose again... and I keep hearin’ the saaame excuses.",
    "category": "Delusion",
    "tags": [
      "same excuses",
      "dazed and confused",
      "matthew mcconaughey",
      "cowboys losses",
      "fan delusion"
    ],
    "qualityScore": 88,
    "qualityReason": "A recognizable Dazed and Confused format that turns endless Cowboys excuses into the punchline. Large readable original image.",
    "sourcePostDate": "2015-09-27",
    "sourceDateBasis": "Verified date of the linked publisher gallery; not an assertion of original meme creation date.",
    "originalCreationDate": null,
    "originalSrc": "https://s.hdnux.com/photos/41/14/67/8703479/4/rawImage.jpg",
    "classic": true,
    "reviewedAt": "2026-09-28",
    "cleanReview": "Pass: football/fan satire, no profanity, slurs, sexual content, or injury/death punchlines.",
    "sha256": "f12c032c169f0a920ffbcd1239ac61bf2abd92a2ac8a51d132c8278b4b4fea4d",
    "classicDateUnknown": false,
    "width": 1165,
    "height": 839,
    "sourceArticleDate": "2015-09-27",
    "sourceArticleDateType": "published",
    "attributionNote": "Publisher date verified on article. Source does not establish the original meme creator or creation date.",
    "type": "meme",
    "contentNote": "Published in Chron’s Week 3 NFL meme gallery on September 27, 2015. Original meme creation date and creator unverified.",
    "dateVerification": "Verified date of the linked publisher gallery; not an assertion of original meme creation date.",
    "bestRoast": false,
    "origin": "community",
    "curated": true,
    "addedAt": "2026-09-28T20:37:11.163Z",
    "src": "./assets/handpicked/community-same-excuses-2015.jpg",
    "preview": "./assets/handpicked/community-same-excuses-2015.jpg",
    "subject": "Dallas Cowboys",
    "featuredRank": -233,
    "reviewed": true
  },
  {
    "type": "meme",
    "origin": "community",
    "category": "Jerry’s World",
    "subject": "Jerry Jones",
    "tags": [
      "Jerry Jones",
      "Dallas Cowboys",
      "Jerry’s World",
      "Front office"
    ],
    "reviewedAt": "2026-09-28",
    "reviewed": true,
    "classic": true,
    "id": "dmn-jerry-fire-the-gm",
    "title": "Maybe I should fire the GM",
    "caption": "JERRY JONES IS THINKING... MAYBE I SHOULD FIRE THE GM?",
    "sourceUrl": "https://www.dallasnews.com/sports/cowboys/2015/10/28/the-best-memes-of-fans-mercilessly-making-fun-of-cowboys-jerry-jones/",
    "sourceName": "Dallas Morning News",
    "author": "SportsDay reader submission",
    "sourcePostDate": "2015-10-28T00:00:00Z",
    "dateVerification": "Dated article October 28, 2015; contributor not individually credited.",
    "width": 830,
    "height": 436,
    "qualityReason": "The owner proposes firing the general manager, who is himself. Short, immediately legible self-own with a recognizable Jerry reaction.",
    "originalSrc": "https://dmn-dallas-news-prod.cdn.arcpublishing.com/resizer/v2/7IPLGUN4JQ3JA7BHE3SNFBPXWE.jpg?auth=4bc162cb7f79f7426e505edfe662642c7412ffd6d3b730927691c5b2d7b8c02e&quality=80&width=830",
    "preview": "./assets/handpicked/dmn-jerry-fire-the-gm.jpg",
    "src": "./assets/handpicked/dmn-jerry-fire-the-gm.jpg",
    "sourceDatePrecision": "day",
    "curated": true,
    "bestRoast": true,
    "featuredRank": -217,
    "addedAt": "2026-09-28T18:44:17.164Z",
    "cleanReview": "Original image visually reviewed: complete readable caption, recognizable Jerry reaction, no profanity.",
    "contentNote": "Classic published in a 2015 Dallas Morning News reader-meme roundup; exact creation date and individual creator are uncredited.",
    "momentTags": [
      "jerry",
      "front-office",
      "blame-game"
    ]
  },
  {
    "id": "imgflip-a57pca",
    "title": "Extreme choking hazard",
    "caption": "WARNING: EXTREME CHOKING HAZARD",
    "originalPostText": "Dallas Cowboys Nuggets Hazard",
    "sourceName": "Imgflip",
    "sourceUrl": "https://imgflip.com/i/a57pca",
    "author": "WillM4",
    "sourcePostDate": null,
    "sourceDateDisplayAtReview": "1 year ago",
    "classic": true,
    "classicDateUnknown": true,
    "type": "meme",
    "origin": "community",
    "category": "Playoffs",
    "subject": "Dallas Cowboys",
    "tags": [
      "Dallas Cowboys",
      "choking",
      "playoffs",
      "nuggets",
      "classic",
      "instant-comeback",
      "after-a-loss",
      "trash-talk"
    ],
    "momentTags": [
      "instant-comeback",
      "after-a-loss",
      "trash-talk"
    ],
    "originalSrc": "https://i.imgflip.com/a57pca.jpg",
    "width": 666,
    "height": 499,
    "reviewedAt": "2026-09-28",
    "qualityScore": 92,
    "bestRoast": true,
    "qualityReason": "Actual Cowboys-branded nuggets become a perfectly specific visual pun: the bold WARNING / EXTREME CHOKING HAZARD text lands immediately at phone size. Cleaner and more pointed than a generic reaction photo.",
    "cleanReview": "Visually inspected original 666×499 JPEG. No profanity, explicit content, politics, slurs, or injury jokes. Choking is an on-field-performance pun.",
    "contentNote": "Classic. The source labels this 1 year ago but does not expose an exact original post date; do not present as fresh.",
    "viewsAtReview": 457,
    "sha256": "808cecf8805d3baef7ad412bf7626adb68ba18ea84e4c1839f79147697d43673",
    "dedupeReview": "ID, source URL, and choking/nuggets caption searched against the existing public catalog: no match found.",
    "preview": "./assets/handpicked/imgflip-a57pca.jpg",
    "src": "./assets/handpicked/imgflip-a57pca.jpg",
    "curated": true,
    "featuredRank": -216,
    "addedAt": "2026-09-28T18:44:17.164Z"
  },
  {
    "id": "pinterest-jerry-quarter-reactions",
    "type": "meme",
    "origin": "community",
    "title": "Four quarters of Jerry",
    "caption": "DALLAS COWBOYS FANS BE LIKE... FIRST QUARTER; SECOND QUARTER; THIRD QUARTER; FOURTH QUARTER",
    "src": "./assets/handpicked/pinterest-jerry-quarter-reactions.jpg",
    "preview": "./assets/handpicked/pinterest-jerry-quarter-reactions.jpg",
    "sourceUrl": "https://www.pinterest.com/pin/jerry-jones-and-how-he-feels-losing-to-the-packers-lo--145804106660201766/",
    "sourceName": "Pinterest",
    "category": "Jerry’s World",
    "subject": "Jerry Jones",
    "tags": [
      "Jerry Jones",
      "Dallas Cowboys",
      "Game day",
      "Collapse",
      "Expectations vs reality"
    ],
    "width": 896,
    "height": 960,
    "qualityReason": "Four different photos build a readable arc from confidence to applause, agitation, and defeat. The sequence supplies the joke instead of a single generic smiling portrait.",
    "curated": true,
    "featuredRank": 3,
    "addedAt": "2026-09-28T14:41:08.937Z",
    "originalSrc": "https://i.pinimg.com/originals/77/73/3f/77733f2459183bdeb41dcdf8cc794511.jpg",
    "bestRoast": true,
    "classic": true
  },
  {
    "id": "imgflip-aims08",
    "type": "meme",
    "origin": "community",
    "title": "Mirror, mirror, same promise",
    "caption": "Dak says this is our year three times; the mirror reflects a trash can.",
    "src": "./assets/handpicked/imgflip-aims08.jpg",
    "preview": "./assets/handpicked/imgflip-aims08.jpg",
    "sourceUrl": "https://imgflip.com/i/aims08",
    "sourceName": "Imgflip",
    "category": "This is our year",
    "subject": "Dak Prescott",
    "tags": [
      "mirror",
      "trash can",
      "this is our year"
    ],
    "width": 595,
    "height": 500,
    "qualityReason": "A full visual transformation supplies the payoff; bold type stays readable.",
    "author": "TrustiGoat",
    "curated": true,
    "featuredRank": 1,
    "addedAt": "2026-09-28T14:41:08.938Z",
    "originalSrc": "https://i.imgflip.com/aims08.jpg"
  },
  {
    "id": "lola-jerry-maher-kicker",
    "type": "meme",
    "origin": "community",
    "title": "Jerry names himself the kicker",
    "caption": "Jerry Jones is photoshopped into a Cowboys uniform after Brett Maher misses another extra point.",
    "src": "./assets/handpicked/lola-jerry-maher-kicker.jpg",
    "preview": "./assets/handpicked/lola-jerry-maher-kicker.jpg",
    "sourceUrl": "https://lolalambchops.com/best-dallas-cowboys-losing-memes/",
    "sourceName": "Lola Lambchops",
    "category": "Jerry’s World",
    "subject": "Jerry Jones",
    "tags": [
      "Brett Maher",
      "extra point",
      "kicker",
      "playoffs"
    ],
    "width": 986,
    "height": 1024,
    "qualityReason": "The absurd uniform composite gives a specific joke about Jerry taking over after the kicking woes.",
    "author": "NFL Memes (@NFL_Memes), as credited in the image",
    "curated": true,
    "featuredRank": 2,
    "addedAt": "2026-09-28T14:41:08.938Z",
    "originalSrc": "https://lolalambchops.com/wp/wp-content/uploads/2023/01/Dallas-Cowboys-Playoff-loss-memes-986x1024.jpg"
  },
  {
    "id": "td-cowboys-20251212-14",
    "type": "meme",
    "origin": "community",
    "title": "Dak opens a bakery",
    "caption": "Dak serves a tray of pastries under the question: Turnovers anyone?",
    "src": "./assets/handpicked/td-cowboys-20251212-14.jpg",
    "preview": "./assets/handpicked/td-cowboys-20251212-14.jpg",
    "sourceUrl": "https://thunderdungeon.com/2025/12/13/20-dallas-cowboys-memes-for-fans-who-love-pain/",
    "sourceName": "Thunder Dungeon",
    "category": "Game day",
    "subject": "Dak Prescott",
    "tags": [
      "turnovers",
      "interceptions",
      "bakery"
    ],
    "width": 600,
    "height": 739,
    "qualityReason": "The literal pastry gag is immediately understandable and tied directly to Dak.",
    "curated": true,
    "featuredRank": 1,
    "addedAt": "2026-09-28T14:41:08.938Z",
    "originalSrc": "https://b3666184.assetcdn.net/3666184/wp-content/uploads/2025/12/dallas-cowboys-memes-14-20251212.jpg?lossy=2&strip=1&webp=1",
    "bestRoast": true,
    "classic": true
  },
  {
    "id": "imgflip-9kpcwr",
    "type": "meme",
    "origin": "community",
    "title": "Jerry Jones every offseason",
    "caption": "SAY THE LINE JERRY; WE'RE GOING ALL IN",
    "src": "./assets/handpicked/imgflip-9kpcwr.jpg",
    "preview": "./assets/handpicked/imgflip-9kpcwr.jpg",
    "sourceUrl": "https://imgflip.com/i/9kpcwr",
    "sourceName": "Imgflip",
    "category": "Jerry’s World",
    "subject": "Jerry Jones",
    "tags": [
      "Jerry Jones",
      "Dallas Cowboys",
      "All in",
      "Offseason",
      "Simpsons"
    ],
    "width": 500,
    "height": 822,
    "qualityReason": "A three-panel Simpsons crowd demands the familiar promise, Jerry delivers it, and the crowd celebrates. The panel progression satirizes the repeating offseason cycle.",
    "author": "NFLDude2K8",
    "curated": true,
    "featuredRank": 4,
    "addedAt": "2026-09-28T14:41:08.938Z",
    "originalSrc": "https://i.imgflip.com/9kpcwr.jpg"
  },
  {
    "id": "td-cowboys-20251212-10",
    "type": "meme",
    "origin": "community",
    "title": "Obsolete since the nineties",
    "caption": "The Cowboys star joins floppy disks and old cameras in a collection of now-useless 1990s favorites.",
    "src": "./assets/handpicked/td-cowboys-20251212-10.jpg",
    "preview": "./assets/handpicked/td-cowboys-20251212-10.jpg",
    "sourceUrl": "https://thunderdungeon.com/2025/12/13/20-dallas-cowboys-memes-for-fans-who-love-pain/",
    "sourceName": "Thunder Dungeon",
    "category": "Offseason",
    "subject": "Dallas Cowboys",
    "tags": [
      "1990s",
      "nostalgia",
      "obsolete",
      "Super Bowl drought"
    ],
    "width": 600,
    "height": 610,
    "qualityReason": "The visual analogy lands instantly and targets the franchise living on old glory.",
    "curated": true,
    "featuredRank": 4,
    "addedAt": "2026-09-28T14:41:08.938Z",
    "originalSrc": "https://b3666184.assetcdn.net/3666184/wp-content/uploads/2025/12/dallas-cowboys-memes-10-20251212.jpg?lossy=2&strip=1&webp=1",
    "bestRoast": true,
    "classic": true
  },
  {
    "id": "td-cowboys-20251212-11",
    "type": "meme",
    "origin": "community",
    "title": "Suddenly everybody has your number",
    "caption": "Two birthday messages versus 47 messages when the Cowboys lose.",
    "src": "./assets/handpicked/td-cowboys-20251212-11.jpg",
    "preview": "./assets/handpicked/td-cowboys-20251212-11.jpg",
    "sourceUrl": "https://thunderdungeon.com/2025/12/13/20-dallas-cowboys-memes-for-fans-who-love-pain/",
    "sourceName": "Thunder Dungeon",
    "category": "Game day",
    "subject": "Dallas Cowboys",
    "tags": [
      "group chat",
      "fans",
      "loss",
      "birthday"
    ],
    "width": 600,
    "height": 604,
    "qualityReason": "A concise modern group-chat joke with strong contrast and almost no reading burden.",
    "curated": true,
    "featuredRank": 2,
    "addedAt": "2026-09-28T14:41:08.938Z",
    "originalSrc": "https://b3666184.assetcdn.net/3666184/wp-content/uploads/2025/12/dallas-cowboys-memes-11-20251212.jpg?lossy=2&strip=1&webp=1",
    "bestRoast": true,
    "classic": true
  },
  {
    "id": "td-cowboys-20251212-13",
    "type": "meme",
    "origin": "community",
    "title": "Geometry of elimination",
    "caption": "Pentagon. Hexagon. Octagon. Seasongon.",
    "src": "./assets/handpicked/td-cowboys-20251212-13.jpg",
    "preview": "./assets/handpicked/td-cowboys-20251212-13.jpg",
    "sourceUrl": "https://thunderdungeon.com/2025/12/13/20-dallas-cowboys-memes-for-fans-who-love-pain/",
    "sourceName": "Thunder Dungeon",
    "category": "Playoffs",
    "subject": "Dallas Cowboys",
    "tags": [
      "elimination",
      "wordplay",
      "season over"
    ],
    "width": 600,
    "height": 688,
    "qualityReason": "A sharp visual pun using the Cowboys star as the final shape; clean and readable.",
    "curated": true,
    "featuredRank": 5,
    "addedAt": "2026-09-28T14:41:08.938Z",
    "originalSrc": "https://b3666184.assetcdn.net/3666184/wp-content/uploads/2025/12/dallas-cowboys-memes-13-20251212.jpg?lossy=2&strip=1&webp=1",
    "bestRoast": true,
    "classic": true
  },
  {
    "id": "pinterest-jerry-april-fools",
    "type": "meme",
    "origin": "community",
    "title": "The retirement announcement",
    "caption": "I’M RETIRING!!!! APRIL FOOLS!!",
    "src": "./assets/handpicked/pinterest-jerry-april-fools.jpg",
    "preview": "./assets/handpicked/pinterest-jerry-april-fools.jpg",
    "sourceUrl": "https://www.pinterest.com/pin/161496336626176247/",
    "sourceName": "Pinterest",
    "category": "Jerry’s World",
    "subject": "Jerry Jones",
    "tags": [
      "Jerry Jones",
      "Dallas Cowboys",
      "Retirement",
      "April Fools",
      "Front office"
    ],
    "width": 735,
    "height": 726,
    "qualityReason": "The apparent retirement announcement and immediate retraction are a complete two-beat joke about fans being unable to escape the same front office.",
    "curated": true,
    "featuredRank": 8,
    "addedAt": "2026-09-28T14:41:08.938Z",
    "originalSrc": "https://i.pinimg.com/736x/a4/02/c1/a402c11a2546763cc6525290893d4a8d.jpg"
  },
  {
    "id": "td-cowboys-20251212-19",
    "type": "meme",
    "origin": "community",
    "title": "Forced to watch the fourth quarter",
    "caption": "Security escorts a fan beneath a joke claiming Cowboys fans are being forced to watch until the end.",
    "src": "./assets/handpicked/td-cowboys-20251212-19.jpg",
    "preview": "./assets/handpicked/td-cowboys-20251212-19.jpg",
    "sourceUrl": "https://thunderdungeon.com/2025/12/13/20-dallas-cowboys-memes-for-fans-who-love-pain/",
    "sourceName": "Thunder Dungeon",
    "category": "Game day",
    "subject": "Dallas Cowboys",
    "tags": [
      "fans",
      "security",
      "loss",
      "fourth quarter"
    ],
    "width": 600,
    "height": 557,
    "qualityReason": "The caption reverses the apparent action in the photo for a sharp, specific suffering-through-a-loss joke.",
    "curated": true,
    "featuredRank": 0,
    "addedAt": "2026-09-28T14:41:08.938Z",
    "originalSrc": "https://b3666184.assetcdn.net/3666184/wp-content/uploads/2025/12/dallas-cowboys-memes-19-20251212.jpg?lossy=2&strip=1&webp=1",
    "bestRoast": true,
    "classic": true
  },
  {
    "id": "jerry-bum-steer",
    "type": "meme",
    "origin": "community",
    "title": "A trophy Jerry can actually win",
    "caption": "BUM STEER 2024",
    "src": "./assets/handpicked/jerry-bum-steer.jpg",
    "preview": "./assets/handpicked/jerry-bum-steer.jpg",
    "sourceUrl": "https://athlonsports.com/nfl/dallas-cowboys/dallas-cowboys-jerry-jones-texas-monthly-bum-steer-award-raccoon-eat-highest-dishonor-award",
    "sourceName": "Athlon Sports / Texas Monthly",
    "category": "Jerry’s World",
    "subject": "Jerry Jones",
    "tags": [
      "Jerry Jones",
      "Dallas Cowboys",
      "Trophy",
      "Satire",
      "2024"
    ],
    "width": 1536,
    "height": 960,
    "qualityReason": "A detailed satirical illustration stages an elaborate Cowboys trophy celebration for the Bum Steer dishonor. The trophy itself reverses the expectation of a championship celebration.",
    "curated": true,
    "featuredRank": 10,
    "addedAt": "2026-09-28T14:41:08.938Z",
    "originalSrc": "https://athlonsports.com/.image/ar_1.91%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cg_faces%3Acenter%2Cq_auto%3Agood%2Cw_1200/MjExNDc1MzY5MTM0NDAwNjcx/cowboys---jerry-bum-steer.jpg"
  },
  {
    "id": "td-cowboys-20251212-16",
    "type": "meme",
    "origin": "community",
    "title": "The only postgame celebration",
    "caption": "A stadium sign says a Cowboys fan celebrates a Super Bowl win by turning off the Xbox.",
    "src": "./assets/handpicked/td-cowboys-20251212-16.jpg",
    "preview": "./assets/handpicked/td-cowboys-20251212-16.jpg",
    "sourceUrl": "https://thunderdungeon.com/2025/12/13/20-dallas-cowboys-memes-for-fans-who-love-pain/",
    "sourceName": "Thunder Dungeon",
    "category": "Delusion",
    "subject": "Dallas Cowboys",
    "tags": [
      "Xbox",
      "Super Bowl",
      "stadium sign",
      "fans"
    ],
    "width": 600,
    "height": 550,
    "qualityReason": "A real readable fan sign gives the simulated-Super-Bowl punchline a different format and clear payoff.",
    "curated": true,
    "featuredRank": 11,
    "addedAt": "2026-09-28T14:41:08.938Z",
    "originalSrc": "https://b3666184.assetcdn.net/3666184/wp-content/uploads/2025/12/dallas-cowboys-memes-16-20251212.jpg?lossy=2&strip=1&webp=1"
  },
  {
    "id": "imgflip-26xql1",
    "type": "gif",
    "origin": "community",
    "title": "Cowboys Fans During Free Agency",
    "caption": "JOOOOOOOOONES!!!!!!!",
    "src": "./assets/handpicked/imgflip-26xql1.gif",
    "preview": "./assets/handpicked/imgflip-26xql1.gif",
    "sourceUrl": "https://imgflip.com/gif/26xql1",
    "sourceName": "Imgflip",
    "category": "Jerry’s World",
    "subject": "Jerry Jones",
    "tags": [
      "Jerry Jones",
      "Dallas Cowboys",
      "Free agency",
      "Frustration",
      "Star Trek"
    ],
    "width": 260,
    "height": 260,
    "qualityReason": "The full animated Kirk scream is retargeted at Jones; a clean, exaggerated fan reaction to an empty free-agency window, with a different visual vocabulary from the catalog’s Jerry interview and suite loops.",
    "poster": "./assets/handpicked/imgflip-26xql1.gif",
    "author": "MicahRobertson1",
    "curated": true,
    "featuredRank": 12,
    "addedAt": "2026-09-28T14:41:08.938Z",
    "originalSrc": "https://i.imgflip.com/26xql1.gif"
  },
  {
    "id": "pinterest-jerry-three-teams",
    "type": "meme",
    "origin": "community",
    "title": "Three teams ahead of you, Jerry",
    "caption": "WE HAVE A GOOD SHOT AT GETTING TO THE PLAYOFFS. WHY NOT US? THREE TEAMS AHEAD OF YOU JERRY!",
    "src": "./assets/handpicked/pinterest-jerry-three-teams.jpg",
    "preview": "./assets/handpicked/pinterest-jerry-three-teams.jpg",
    "sourceUrl": "https://www.pinterest.com/pin/jerry-jones-sucks--316237205066524284/",
    "sourceName": "Pinterest",
    "category": "Jerry’s World",
    "subject": "Jerry Jones",
    "tags": [
      "Jerry Jones",
      "Dallas Cowboys",
      "Playoffs",
      "Optimism",
      "Reality check"
    ],
    "width": 532,
    "height": 720,
    "qualityReason": "Jerry’s optimistic press conference is answered by the emphatic telephone scene from Planes, Trains and Automobiles. The visual exchange gives the standings joke a second character and a punchline.",
    "curated": true,
    "featuredRank": 13,
    "addedAt": "2026-09-28T14:41:08.938Z",
    "originalSrc": "https://i.pinimg.com/564x/2c/91/f8/2c91f883565d8f191b77c92caff07f96.jpg"
  },
  {
    "id": "td-cowboys-20251212-1",
    "type": "meme",
    "origin": "community",
    "title": "Same division, same story",
    "caption": "An NFC East comparison ends with Romo and Dak labeled regular-season merchants.",
    "src": "./assets/handpicked/td-cowboys-20251212-1.jpg",
    "preview": "./assets/handpicked/td-cowboys-20251212-1.jpg",
    "sourceUrl": "https://thunderdungeon.com/2025/12/13/20-dallas-cowboys-memes-for-fans-who-love-pain/",
    "sourceName": "Thunder Dungeon",
    "category": "Playoffs",
    "subject": "Dak Prescott, Tony Romo",
    "tags": [
      "regular season",
      "playoffs",
      "NFC East",
      "Tony Romo",
      "Dak Prescott"
    ],
    "width": 600,
    "height": 750,
    "qualityReason": "A clear four-part setup saves the Cowboys roast for the final row; specific to their postseason pattern.",
    "curated": true,
    "featuredRank": 14,
    "addedAt": "2026-09-28T14:41:08.938Z",
    "originalSrc": "https://b3666184.assetcdn.net/3666184/wp-content/uploads/2025/12/dallas-cowboys-memes-1-20251212.jpg?lossy=2&strip=1&webp=1"
  },
  {
    "id": "td-cowboys-20251212-3",
    "type": "meme",
    "origin": "community",
    "title": "The early interception fork",
    "caption": "An early Dak interception opens two paths: Hall of Fame quarterback play or the worst game ever.",
    "src": "./assets/handpicked/td-cowboys-20251212-3.jpg",
    "preview": "./assets/handpicked/td-cowboys-20251212-3.jpg",
    "sourceUrl": "https://thunderdungeon.com/2025/12/13/20-dallas-cowboys-memes-for-fans-who-love-pain/",
    "sourceName": "Thunder Dungeon",
    "category": "Game day",
    "subject": "Dak Prescott",
    "tags": [
      "interceptions",
      "quarterback",
      "inconsistency"
    ],
    "width": 600,
    "height": 600,
    "qualityReason": "A readable two-path visual captures the peculiar uncertainty of watching Dak after an early pick.",
    "curated": true,
    "featuredRank": 15,
    "addedAt": "2026-09-28T14:41:08.939Z",
    "originalSrc": "https://b3666184.assetcdn.net/3666184/wp-content/uploads/2025/12/dallas-cowboys-memes-3-20251212.jpg?lossy=2&strip=1&webp=1"
  },
  {
    "id": "td-cowboys-20251212-4",
    "type": "meme",
    "origin": "community",
    "title": "More believable than a Dallas Super Bowl",
    "caption": "Bigfoot riding the Loch Ness Monster is more believable than the Cowboys going to the Super Bowl.",
    "src": "./assets/handpicked/td-cowboys-20251212-4.jpg",
    "preview": "./assets/handpicked/td-cowboys-20251212-4.jpg",
    "sourceUrl": "https://thunderdungeon.com/2025/12/13/20-dallas-cowboys-memes-for-fans-who-love-pain/",
    "sourceName": "Thunder Dungeon",
    "category": "Delusion",
    "subject": "Dallas Cowboys",
    "tags": [
      "Super Bowl",
      "Bigfoot",
      "Loch Ness",
      "delusion"
    ],
    "width": 600,
    "height": 571,
    "qualityReason": "An absurd composite delivers one immediate Cowboys-specific punchline; no filler reaction image.",
    "curated": true,
    "featuredRank": 16,
    "addedAt": "2026-09-28T14:41:08.939Z",
    "originalSrc": "https://b3666184.assetcdn.net/3666184/wp-content/uploads/2025/12/dallas-cowboys-memes-4-20251212.jpg?lossy=2&strip=1&webp=1"
  },
  {
    "id": "td-cowboys-20251212-8",
    "type": "meme",
    "origin": "community",
    "title": "The seasonal wardrobe change",
    "caption": "After playoff elimination, Homer retreats in a Cowboys jersey and returns in Lakers and Yankees gear.",
    "src": "./assets/handpicked/td-cowboys-20251212-8.jpg",
    "preview": "./assets/handpicked/td-cowboys-20251212-8.jpg",
    "sourceUrl": "https://thunderdungeon.com/2025/12/13/20-dallas-cowboys-memes-for-fans-who-love-pain/",
    "sourceName": "Thunder Dungeon",
    "category": "Playoffs",
    "subject": "Dallas Cowboys",
    "tags": [
      "bandwagon",
      "fans",
      "Homer Simpson",
      "Lakers",
      "Yankees"
    ],
    "width": 600,
    "height": 752,
    "qualityReason": "A complete four-panel visual joke about bandwagon fandom, with the team logos carrying the punchline.",
    "curated": true,
    "featuredRank": 17,
    "addedAt": "2026-09-28T14:41:08.939Z",
    "originalSrc": "https://b3666184.assetcdn.net/3666184/wp-content/uploads/2025/12/dallas-cowboys-memes-8-20251212.jpg?lossy=2&strip=1&webp=1"
  },
  {
    "id": "td-cowboys-20251212-15",
    "type": "meme",
    "origin": "community",
    "title": "The VCR consolation plan",
    "caption": "A Cowboys fan is consoled with an invitation to watch the Super Bowl on the VCR.",
    "src": "./assets/handpicked/td-cowboys-20251212-15.jpg",
    "preview": "./assets/handpicked/td-cowboys-20251212-15.jpg",
    "sourceUrl": "https://thunderdungeon.com/2025/12/13/20-dallas-cowboys-memes-for-fans-who-love-pain/",
    "sourceName": "Thunder Dungeon",
    "category": "Playoffs",
    "subject": "Dallas Cowboys",
    "tags": [
      "VCR",
      "1990s",
      "nostalgia",
      "fans"
    ],
    "width": 600,
    "height": 511,
    "qualityReason": "A specific visual consolation joke gives the old-glory theme more personality than a generic VHS statement.",
    "curated": true,
    "featuredRank": 18,
    "addedAt": "2026-09-28T14:41:08.939Z",
    "originalSrc": "https://b3666184.assetcdn.net/3666184/wp-content/uploads/2025/12/dallas-cowboys-memes-15-20251212.jpg?lossy=2&strip=1&webp=1"
  },
  {
    "id": "td-cowboys-20251212-18",
    "type": "meme",
    "origin": "community",
    "title": "Believing in impossible things",
    "caption": "The meme defends children who believe in Santa by pointing to grown-ups who believe in the Cowboys.",
    "src": "./assets/handpicked/td-cowboys-20251212-18.jpg",
    "preview": "./assets/handpicked/td-cowboys-20251212-18.jpg",
    "sourceUrl": "https://thunderdungeon.com/2025/12/13/20-dallas-cowboys-memes-for-fans-who-love-pain/",
    "sourceName": "Thunder Dungeon",
    "category": "Delusion",
    "subject": "Dallas Cowboys",
    "tags": [
      "Santa",
      "Christmas",
      "adult fans",
      "belief"
    ],
    "width": 600,
    "height": 761,
    "qualityReason": "The joke explicitly targets adult fan optimism; friendly imagery supports a clean roast.",
    "curated": true,
    "featuredRank": 19,
    "addedAt": "2026-09-28T14:41:08.939Z",
    "originalSrc": "https://b3666184.assetcdn.net/3666184/wp-content/uploads/2025/12/dallas-cowboys-memes-18-20251212.jpg?lossy=2&strip=1&webp=1"
  },
  {
    "id": "imgflip-7f8f7k",
    "type": "meme",
    "origin": "community",
    "title": "Say the line, Cowboys",
    "caption": "The Simpsons class prompts the Cowboys after signing Brandin Cooks: This is our year.",
    "src": "./assets/handpicked/imgflip-7f8f7k.jpg",
    "preview": "./assets/handpicked/imgflip-7f8f7k.jpg",
    "sourceUrl": "https://imgflip.com/i/7f8f7k",
    "sourceName": "Imgflip",
    "category": "This is our year",
    "subject": "Dallas Cowboys",
    "tags": [
      "Simpsons",
      "Brandin Cooks",
      "offseason hype",
      "this is our year"
    ],
    "width": 500,
    "height": 822,
    "qualityReason": "A recognizable three-panel ritual makes fun of fan optimism restarting after every signing. The original image misspells Brandin as Branding.",
    "author": "Mb15",
    "curated": true,
    "featuredRank": 20,
    "addedAt": "2026-09-28T14:41:08.939Z",
    "originalSrc": "https://i.imgflip.com/7f8f7k.jpg"
  },
  {
    "id": "imgflip-8cctb8",
    "type": "meme",
    "origin": "community",
    "title": "Superman until January",
    "caption": "Superman represents the regular season; the bumbling Greatest American Hero represents the playoffs.",
    "src": "./assets/handpicked/imgflip-8cctb8.jpg",
    "preview": "./assets/handpicked/imgflip-8cctb8.jpg",
    "sourceUrl": "https://imgflip.com/i/8cctb8",
    "sourceName": "Imgflip",
    "category": "Playoffs",
    "subject": "Dallas Cowboys",
    "tags": [
      "regular season",
      "Superman",
      "Greatest American Hero",
      "playoff collapse"
    ],
    "width": 500,
    "height": 1291,
    "qualityReason": "Two contrasting superhero images make the postseason collapse joke immediately visual.",
    "author": "kevro1977",
    "curated": true,
    "featuredRank": 21,
    "addedAt": "2026-09-28T14:41:08.939Z",
    "originalSrc": "https://i.imgflip.com/8cctb8.jpg"
  },
  {
    "id": "lola-woody-superbowl",
    "type": "meme",
    "origin": "community",
    "title": "Woody cannot explain the Super Bowl",
    "caption": "Buzz asks what a Super Bowl is. Woody does not know because he is a cowboy.",
    "src": "./assets/handpicked/lola-woody-superbowl.jpg",
    "preview": "./assets/handpicked/lola-woody-superbowl.jpg",
    "sourceUrl": "https://lolalambchops.com/best-dallas-cowboys-losing-memes/",
    "sourceName": "Lola Lambchops",
    "category": "Playoffs",
    "subject": "Dallas Cowboys",
    "tags": [
      "Toy Story",
      "Woody",
      "Buzz Lightyear",
      "Super Bowl drought"
    ],
    "width": 600,
    "height": 600,
    "qualityReason": "The familiar Toy Story characters give the cowboy wordplay a crisp two-line punchline.",
    "curated": true,
    "featuredRank": 22,
    "addedAt": "2026-09-28T14:41:08.939Z",
    "originalSrc": "https://lolalambchops.com/wp/wp-content/uploads/2023/01/Dallas-Cowboys-memes.jpg"
  },
  {
    "id": "imgflip-4k3ko5",
    "type": "meme",
    "origin": "community",
    "title": "Jerry Knows Best",
    "caption": "SORRY. NOT SORRY.",
    "src": "./assets/handpicked/imgflip-4k3ko5.jpg",
    "preview": "./assets/handpicked/imgflip-4k3ko5.jpg",
    "sourceUrl": "https://imgflip.com/i/4k3ko5",
    "sourceName": "Imgflip",
    "category": "Jerry’s World",
    "subject": "Jerry Jones",
    "tags": [
      "Jerry Jones",
      "Dallas Cowboys",
      "Press conference",
      "Accountability",
      "Radio"
    ],
    "width": 645,
    "height": 500,
    "qualityReason": "The mock royal apology pairs Mel Brooks’ king with the reported Jerry radio-host apology, turning a public-relations non-apology into the visual punchline.",
    "curated": true,
    "featuredRank": 23,
    "addedAt": "2026-09-28T14:41:08.939Z",
    "originalSrc": "https://i.imgflip.com/4k3ko5.jpg"
  },
  {
    "id": "dmn-jerry-cassel-player-week",
    "type": "meme",
    "origin": "community",
    "title": "The other team’s player of the week",
    "caption": "THE FACE YOU MAKE WHEN MATT CASSEL IS NAMED GIANTS PLAYER OF THE WEEK.",
    "src": "./assets/handpicked/dmn-jerry-cassel-player-week.jpg",
    "preview": "./assets/handpicked/dmn-jerry-cassel-player-week.jpg",
    "sourceUrl": "https://www.dallasnews.com/sports/cowboys/2015/10/28/the-best-memes-of-fans-mercilessly-making-fun-of-cowboys-jerry-jones/",
    "sourceName": "The Dallas Morning News",
    "category": "Jerry’s World",
    "subject": "Jerry Jones",
    "tags": [
      "Jerry Jones",
      "Dallas Cowboys",
      "Quarterback",
      "Interceptions",
      "Rivalry"
    ],
    "width": 830,
    "height": 436,
    "qualityReason": "A specific turnover punchline makes the Cowboys quarterback the rival Giants’ most valuable contributor. Jerry’s tight-lipped expression completes a joke that reads without additional context.",
    "curated": true,
    "featuredRank": 24,
    "addedAt": "2026-09-28T14:41:08.939Z",
    "originalSrc": "https://dmn-dallas-news-prod.cdn.arcpublishing.com/resizer/v2/B7VPRC6DCDWJS57DD4G2HJSEXI.jpg?auth=a79cb376129bdb1f7bfaa8916334981053f239518e734207d35e811d27659419&quality=80&width=830"
  }
];
