// Editorial selection is explicit; recency uses original post dates, never import time.
export const curation = { reviewedAt: '2026-09-28', cadence: 'Tuesdays · 10 a.m. ET', windowDays: 30 };
export const reactions = [
  ['interception','Interception',/intercept|pick six|pick-six|turnover/i],
  ['missed-kick','Missed kick',/missed kick|kicker|field goal|extra point|maher/i],
  ['blown-lead','Blown lead',/blown|collapse|chok|fourth quarter|4th quarter|comeback/i],
  ['loss','Final whistle',/loss|lose|lost|defeat|eliminat|playoff|cry|crying/i],
  ['jerry','Jerry reaction',/jerry|owner|gm|front office/i]
];
export function matchesReaction(m,key) {const r=reactions.find(r=>r[0]===key);return !r||r[2].test([m.title,m.caption,m.top,m.bottom,m.subject,m.category,...m.tags||[]].join(' '));}
export function isFresh(m,now=Date.now()){const date=Date.parse(m.sourcePostDate);return Number.isFinite(date)&&date<=now&&now-date<=curation.windowDays*86400000;}
export function qualityLabel(m,now=Date.now()){return isFresh(m,now)?(m.olderFootage?'Recent post · reused footage':'Recent post'):m.sourcePostDate?'Archive pick':'Classic · date unverified';}
export function bestEligible(m,ratings={},now=Date.now()){return m.type!=='template'&&ratings[m.id]!==-1&&(ratings[m.id]===1||m.bestRoast===true&&(m.classic===true||isFresh(m,now)));}
export function qualitySort(a,b,ratings={},now=Date.now()){return (ratings[b.id]||0)-(ratings[a.id]||0)||Number(isFresh(b,now))-Number(isFresh(a,now))||(a.featuredRank??9999)-(b.featuredRank??9999);}
function mediaKey(m){const raw=m.originalSrc||m.src;if(!raw||raw.startsWith('data:')||m.top||m.bottom)return null;try{const u=new URL(raw,'https://local.invalid');u.hash='';for(const k of ['width','height','w','h','quality','q','name'])u.searchParams.delete(k);u.searchParams.sort();return u.href+'|'+String(m.caption||'').trim().toLowerCase().replace(/\s+/g,' ');}catch{return raw+'|'+String(m.caption||'').trim();}}
export function auditCatalog(items){const groups=new Map(),issues=[];for(const m of items){if(m.type==='template')continue;const key=mediaKey(m);if(key){const group=groups.get(key)||[];group.push(m);groups.set(key,group);}if(m.width&&m.height&&Math.min(m.width,m.height)<240)issues.push({item:m,reason:`Small source: ${m.width} × ${m.height}`,kind:'resolution'});}for(const group of groups.values())if(group.length>1)for(const m of group.slice(1))issues.push({item:m,reason:`Same media as “${group[0].title}”`,kind:'duplicate',original:group[0]});return issues;}
export function createCleanup({items,remove,open,toast,removed}){
  const dialog=document.createElement('dialog');dialog.className='cleanup-dialog';document.body.append(dialog);let issues=[],controller;
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function render(){const shown=issues.filter(x=>!removed().has(x.item.id));dialog.innerHTML=`<div class="cleanup-head"><h2>Library cleanup</h2><button data-close aria-label="Close cleanup">×</button></div><p>Review duplicate media, small sources, and unavailable previews. Removing an item is reversible.</p><div class="cleanup-actions"><button class="button outline" data-scan>Check 60 archive previews</button><button class="button outline" data-stop ${controller?'':'hidden'}>Stop scan</button><span role="status" id="cleanup-status">${shown.length} items to review</span></div><div class="cleanup-results">${shown.map(x=>`<article><img src="${esc(x.item.preview||x.item.poster||x.item.src)}" alt="" loading="lazy"><div><strong>${esc(x.item.title)}</strong><p>${esc(x.reason)}</p><button class="button outline" data-open="${esc(x.item.id)}">Review</button>${x.original?`<button class="button outline" data-open="${esc(x.original.id)}">Compare original</button>`:''}<button class="button outline" data-remove="${esc(x.item.id)}">Remove</button></div></article>`).join('')||'<p>No issues found in the metadata checked. The preview scan can find more.</p>'}</div>`;}
  dialog.addEventListener('close',()=>{controller?.abort();controller=null;});
  dialog.onclick=async e=>{const b=e.target.closest('button');if(!b)return;e.stopPropagation();if(b.hasAttribute('data-close'))dialog.close();if(b.dataset.open){dialog.close();open(b.dataset.open);}if(b.dataset.remove){b.disabled=true;await remove(b.dataset.remove,true);render();}if(b.hasAttribute('data-stop')){controller?.abort();controller=null;render();}if(b.hasAttribute('data-scan'))scan();};
  let offset=0;
  async function scan(){controller?.abort();const run=new AbortController();controller=run;render();dialog.querySelector('[data-scan]').disabled=true;const candidates=items().filter(m=>!m.curated&&m.type!=='template'),batch=candidates.slice(offset,offset+60);offset=(offset+60>=candidates.length)?0:offset+60;let next=0,done=0;
    async function inspect(m){return new Promise(resolve=>{const img=new Image();let timer;const finish=reason=>{clearTimeout(timer);run.signal.removeEventListener('abort',abort);img.onload=img.onerror=null;if(reason&&!issues.some(x=>x.item.id===m.id))issues.push({item:m,reason,kind:'preview'});resolve();};const abort=()=>{img.src='';finish();};img.onload=()=>finish(Math.min(img.naturalWidth,img.naturalHeight)<160?`Small preview: ${img.naturalWidth} × ${img.naturalHeight}`:null);img.onerror=()=>finish('Preview did not load. Check the original source before removing.');run.signal.addEventListener('abort',abort,{once:true});timer=setTimeout(()=>finish('Preview timed out. It may be temporarily unavailable.'),7000);img.src=m.poster||m.preview||m.src;});}
    await Promise.all(Array.from({length:4},async()=>{while(next<batch.length&&!run.signal.aborted){await inspect(batch[next++]);done++;const status=dialog.querySelector('#cleanup-status');if(status)status.textContent=`Checked ${done} / ${batch.length}`;}}));if(controller!==run)return;controller=null;render();toast(`Checked ${done} previews. Review flagged items before removing.`);
  }
  return{show(){issues=auditCatalog(items());render();dialog.showModal();}};
}
