import { mountOverlayControls } from './overlay-controls.js';
import { mountSharePresets } from './share-presets.js';
import { createGifSource } from './assets/gif-decoder/gif-source.js';
import { createVideoTrimmer } from './video-trimmer.js';
import { createXImporter } from './x-importer.js';

const MAX_SECONDS = 8;
const MAX_BYTES = 100 * 1024 * 1024;
const abortError = () => new DOMException('Cancelled', 'AbortError');

function waitForMedia(video, event, { signal, timeout = 15000 } = {}) {
  return new Promise((resolve, reject) => {
    const cleanup = () => { clearTimeout(timer); video.removeEventListener(event, done); video.removeEventListener('error', failed); signal?.removeEventListener('abort', cancelled); };
    const done = () => { cleanup(); resolve(); };
    const failed = () => { cleanup(); reject(new Error('This video could not be decoded. Try an H.264 MP4 file.')); };
    const cancelled = () => { cleanup(); reject(abortError()); };
    const timer = setTimeout(() => { cleanup(); reject(new Error('The video took too long to load. Try a shorter H.264 MP4 file.')); }, timeout);
    video.addEventListener(event, done, { once: true });
    video.addEventListener('error', failed, { once: true });
    signal?.addEventListener('abort', cancelled, { once: true });
    if (signal?.aborted) cancelled();
  });
}

async function seek(video, time, signal) {
  if (signal?.aborted) throw abortError();
  if (Math.abs(video.currentTime - time) < 0.001 && video.readyState >= 2 && !video.seeking) return;
  const ready = waitForMedia(video, 'seeked', { signal });
  video.currentTime = time;
  await ready;
  if (video.readyState < 2) await waitForMedia(video, 'loadeddata', { signal });
}

import { framePlan, gifFramePlan, renderVideoFrame, cropGeometry } from './video-render.js';
import { mountCaptionPacks } from './caption-packs.js';

export function createVideoMaker(root, { toast, downloadBlob, onSave, onSaveProject, onImage, onSaveImage }) {
  root.innerHTML = `<div class="maker-header"><div><span class="eyebrow">VIDEO STUDIO</span><h1>EDIT. CAPTION. <span>LOOP.</span></h1><p>Paste an X / Twitter link or upload a file. Trim, caption, and export your clip.</p></div><button class="back-link" data-view="library">← Back to library</button></div>
  <div class="creator-switch"><button data-view="maker">Image meme</button><button class="active" aria-current="page">Video studio</button><button data-view="projects">Editable projects</button></div>
  <section class="x-import-panel" id="x-import-panel" aria-label="Import X or Twitter posts"></section>
  <div class="video-layout"><div><div class="video-empty" id="video-empty"><span>▷</span><h2>Start with a link or a file</h2><p>Paste a public X / Twitter post to bring its media straight into the editor.</p><button class="button primary" id="video-link-empty">↗ Paste X / Twitter link</button><button class="button outline" id="video-pick-empty">↑ Upload from device</button><p class="saved-note">Local files: MP4, WebM, MOV or GIF<br>Videos up to 100 MB · GIFs up to 20 MB</p></div>
  <div id="video-preview-wrap" hidden><div class="video-frame rendered-video"><video id="source-video" muted playsinline preload="auto" aria-hidden="true"></video><canvas id="video-render-preview" aria-label="Edited clip preview"></canvas></div><div id="video-trimmer"></div><p id="video-file-info" class="preview-note"></p><div id="original-video-actions" class="original-video-actions" hidden><button class="button outline" id="video-save-original">♡ Save original video</button><button class="button outline" id="video-download-original">↓ Download original MP4</button><p class="saved-note" id="video-original-note"></p></div></div>
  <div id="gif-result" class="gif-result" hidden><div class="result-heading"><h2 id="video-result-title">Export preview</h2><span id="gif-result-info"></span></div><img id="gif-result-image" alt="Preview of your generated GIF"><video id="mp4-result-video" controls muted loop playsinline hidden></video><div class="export-actions"><button class="button primary" id="video-download">↓ Download</button><button class="button outline" id="video-save">♡ Save to library</button></div><p class="saved-note" id="video-save-note"></p></div>
  </div><div class="editor-panel"><button class="button primary upload-button" id="video-link">↗ Paste X / Twitter link</button><button class="button outline upload-button" id="video-pick">↑ Upload from device</button><input type="file" id="video-file" accept="video/mp4,video/webm,video/quicktime,video/*,image/gif,.gif,.mov" hidden>
  <label class="check-label video-jerry"><input type="checkbox" id="video-jerry-tag"> Add to Jerry’s World</label><fieldset id="video-controls" disabled>
  <div class="editor-section"><span class="control-label">01 / Captions</span><label class="field"><span>Top text</span><textarea id="video-top" maxlength="120" placeholder="Optional top caption"></textarea></label><label class="field"><span>Bottom text</span><textarea id="video-bottom" maxlength="120" placeholder="Optional bottom caption"></textarea></label><div id="video-caption-packs"></div><details class="overlay-details"><summary>Style, drag placement & timed captions</summary><div id="video-overlay-controls"></div></details><label class="field"><span>Title / project name</span><input id="video-title" type="text" maxlength="100" placeholder="Name your clip"></label></div>
  <div class="editor-section"><span class="control-label">02 / Crop & playback</span><div class="editor-row"><label class="field"><span>Crop</span><select id="video-aspect"><option value="original">Original</option><option value="1:1">Square · 1:1</option><option value="4:5">Portrait · 4:5</option><option value="9:16">Vertical · 9:16</option><option value="16:9">Wide · 16:9</option></select></label><label class="field"><span>Speed</span><select id="video-speed"><option value="0.5">Slow · ½×</option><option value="1" selected>Normal · 1×</option><option value="2">Fast · 2×</option></select></label></div>
  <label class="field"><span>Zoom <output id="video-zoom-value">1.0×</output></span><input type="range" id="video-zoom" aria-label="Video zoom" min="1" max="3" value="1" step="0.05"></label><div class="editor-row"><label class="field"><span>Horizontal position</span><input type="range" id="video-pan-x" min="-1" max="1" value="0" step="0.02"></label><label class="field"><span>Vertical position</span><input type="range" id="video-pan-y" min="-1" max="1" value="0" step="0.02"></label></div><label class="field"><span>Playback</span><select id="video-playback"><option value="forward">Forward</option><option value="reverse">Reverse</option><option value="pingpong">Ping-pong · forward & back</option></select></label></div>
  <div class="editor-section"><span class="control-label">03 / Export</span><div id="video-share-presets"></div><label class="field"><span>Format</span><select id="video-format"><option value="gif">Animated GIF</option><option value="mp4">Captioned MP4</option></select></label><div class="editor-row"><label class="field"><span>Size</span><select id="video-size"><option value="320">Small · 320 px</option><option value="480" selected>Standard · 480 px</option><option value="720">Large · 720 px (MP4)</option></select></label><label class="field"><span>Frame rate</span><select id="video-fps"><option value="0" disabled>Original GIF timing</option><option value="5">5 fps</option><option value="10" selected>10 fps</option><option value="15">15 fps</option><option value="30">30 fps (MP4)</option></select></label></div><p class="saved-note" id="video-format-note">Exports are silent. Originals retain their sound.</p><button class="button primary upload-button" id="video-convert">Create GIF</button></div>
  <div class="editor-section project-save"><button class="button outline upload-button" id="video-save-project">Save editable project</button><p class="saved-note">Keeps the original and your edits for later. Source files up to 20 MB.</p></div></fieldset><p id="video-status" class="video-status" role="status" aria-live="polite"></p><div id="video-progress-wrap" hidden><progress id="video-progress" max="100" value="0" aria-label="Video export progress"></progress><button class="button outline" id="video-cancel">Cancel</button></div></div></div>`;
  const $=s=>root.querySelector(s),nativeVideo=$('#source-video'),preview=$('#video-render-preview');let video=nativeVideo;
  let sourceUrl,result,resultUrl,loadController,encodeController,ready=false,sourceFile,sourceMeta={},originalId,sourceGeneration=0,projectId=null,projectSaving=false;let overlayControls;
  const status=(message,error=false)=>{$('#video-status').textContent=message;$('#video-status').classList.toggle('error',error);};
  const importer=createXImporter($('#x-import-panel'),{onFile:async(file,meta)=>{if(file.type.startsWith('image/'))return onImage(file,meta);const loaded=await loadFile(file,meta);if(loaded)$('#video-preview-wrap').scrollIntoView({behavior:'smooth',block:'start'});return loaded;},onSaveFile:(file,meta)=>file.type.startsWith('image/')?onSaveImage(file,{...meta,jerry:$('#video-jerry-tag').checked}):saveImportedFile(file,meta)});
  const trimmer=createVideoTrimmer($('#video-trimmer'),video,{onChange(){discardResult();validate();drawPreview();},onFrame:drawPreview});
  const defaults={aspect:'original',speed:1,zoom:1,panX:0,panY:0,playback:'forward',format:'gif',edge:480,fps:10,top:'',bottom:''};
  const fields={aspect:'video-aspect',speed:'video-speed',zoom:'video-zoom',panX:'video-pan-x',panY:'video-pan-y',playback:'video-playback',format:'video-format',edge:'video-size',fps:'video-fps',top:'video-top',bottom:'video-bottom'};
  function clip(){const s={...trimmer.getRange(),version:1,title:$('#video-title').value.trim()||'My Cowboys clip',jerry:$('#video-jerry-tag').checked};for(const [key,id] of Object.entries(fields))s[key]=typeof defaults[key]==='number'?Number($('#'+id).value):$('#'+id).value;return overlayControls?overlayControls.read(s):s;}
  function applySettings(s){for(const [key,id]of Object.entries(fields))$('#'+id).value=s[key]??defaults[key];overlayControls?.apply(s);trimmer.setPlaybackOptions(clip());updateFormat();drawPreview();}
  function drawPreview(){if(!ready||video.readyState<2||video.seeking)return;const g=renderVideoFrame(preview,video,clip());$('.video-frame').style.aspectRatio=`${g.width} / ${g.height}`;}
  function updateFormat(){if(!video.frames&&$('#video-fps').value==='0')$('#video-fps').value='10';$('#video-fps option[value="0"]').disabled=!video.frames;const gif=$('#video-format').value==='gif';$('#video-size option[value="720"]').disabled=gif;$('#video-fps option[value="30"]').disabled=gif;if(gif&&$('#video-size').value==='720')$('#video-size').value='480';if(gif&&$('#video-fps').value==='30')$('#video-fps').value='15';$('#video-convert').textContent=gif?'Create GIF':'Create MP4';$('#video-zoom-value').textContent=Number($('#video-zoom').value).toFixed(2)+'×';}
  function exportPlan(s){const plan=framePlan(s,video.frames);return s.format==='gif'?gifFramePlan(plan):plan;}
  function validate(){const s=clip(),valid=ready&&trimmer.valid()&&s.end<=video.duration+.01;$('#video-convert').disabled=!valid;$('#video-play-clip').disabled=!valid;$('#video-save-project').disabled=!valid||projectSaving;const p=valid?exportPlan(s):null;$('#video-clip-info').textContent=valid?`${(s.end-s.start).toFixed(2)} s selected · ${p.duration.toFixed(2)} s output · ${p.times.length} frames`:'Select 0.2–8 seconds within the video.';return valid;}
  function discardResult(){if(resultUrl)URL.revokeObjectURL(resultUrl);resultUrl=null;result=null;$('#gif-result').hidden=true;$('#gif-result-image').removeAttribute('src');$('#mp4-result-video').pause();$('#mp4-result-video').removeAttribute('src');}
  function cancel(){encodeController?.abort();trimmer.cancel();importer.cancel();loadController?.abort();$('#mp4-result-video').pause();}
  async function loadFile(file,meta={}){
    if(!file||meta.signal?.aborted)return false;
    const isGif=file.type==='image/gif'||/\.gif$/i.test(file.name);if(!(isGif||file.type.startsWith('video/')||/\.(mp4|webm|mov|m4v)$/i.test(file.name)))throw new Error('Choose an MP4, WebM, MOV, or animated GIF.');
    if(file.size>MAX_BYTES)throw new Error('Choose a video smaller than 100 MB.');
    encodeController?.abort();trimmer.cancel();loadController?.abort();sourceGeneration++;sourceFile=null;sourceMeta={};originalId=null;projectId=null;$('#original-video-actions').hidden=true;
    const controller=new AbortController();loadController=controller;const abortImport=()=>controller.abort();meta.signal?.addEventListener('abort',abortImport,{once:true});
    ready=false;discardResult();$('#video-controls').disabled=true;trimmer.setDisabled(true);if(sourceUrl)URL.revokeObjectURL(sourceUrl);sourceUrl=URL.createObjectURL(file);video.destroy?.();video=nativeVideo;status(isGif?'Decoding animated GIF…':'Loading video…');$('#video-preview-wrap').hidden=false;$('#video-empty').hidden=true;
    try{if(isGif){video=await createGifSource(file,{signal:controller.signal});}else{const loaded=waitForMedia(video,'loadeddata',{signal:controller.signal});video.src=sourceUrl;video.load();await loaded;}if(!Number.isFinite(video.duration)||video.duration<.2||!video.videoWidth||!video.videoHeight)throw new Error('This video has no usable duration. Try an H.264 MP4.');if(controller.signal.aborted)return false;
      trimmer.setSource(video);ready=true;sourceFile=file;sourceMeta=meta;originalId='custom-'+crypto.randomUUID();$('#video-controls').disabled=false;applySettings({...defaults,top:String(meta.caption||'').slice(0,120),...(isGif?{fps:0}:{})});trimmer.load(sourceUrl,video.duration,video.getThumbnail?.bind(video));trimmer.setDisabled(false);overlayControls?.refresh();$('#video-title').value=(meta.title||file.name.replace(/\.[^.]+$/,'')).slice(0,100);$('#video-file-info').textContent=`${file.name} · ${video.duration.toFixed(1)} s · ${video.videoWidth} × ${video.videoHeight}`;$('#original-video-actions').hidden=file.type!=='video/mp4';$('#video-save-original').disabled=file.size>20*1024*1024;$('#video-original-note').textContent=file.size>20*1024*1024?'Original saves and projects support files up to 20 MB. Trim and export a smaller clip.':'';drawPreview();validate();status('Drag the handles to trim. Loop the preview to fine-tune your edit.');return true;
    }catch(error){if(loadController===controller){status(error.name==='AbortError'?'Video loading cancelled.':error.message,error.name!=='AbortError');$('#video-preview-wrap').hidden=true;$('#video-empty').hidden=false;}return false;}finally{meta.signal?.removeEventListener('abort',abortImport);if(loadController===controller)loadController=null;}
  }
  overlayControls=mountOverlayControls($('#video-overlay-controls'),preview,{getSettings:clip,getDuration:()=>video.duration,getSourceTime:()=>video.currentTime,onChange(){discardResult();validate();drawPreview();}});
  mountSharePresets($('#video-share-presets'),preset=>{const current=clip();applySettings({...current,...preset,overlays:{...current.overlays,safeInset:preset.safeInset}});discardResult();validate();});
  $('#video-link').onclick=$('#video-link-empty').onclick=()=>importer.focus();
  $('#video-pick').onclick=$('#video-pick-empty').onclick=()=>$('#video-file').click();$('#video-file').onchange=e=>{const file=e.target.files?.[0];e.target.value='';importer.cancel();loadFile(file).catch(e=>status(e.message,true));};
  for(const id of Object.values(fields))$('#'+id).addEventListener('input',()=>{discardResult();updateFormat();if(['video-speed','video-playback'].includes(id))trimmer.setPlaybackOptions(clip());validate();drawPreview();overlayControls?.refresh();});
  mountCaptionPacks($('#video-caption-packs'),c=>{$('#video-top').value=c.top;$('#video-bottom').value=c.bottom;$('#video-jerry-tag').checked=true;discardResult();validate();drawPreview();});
  $('#video-cancel').onclick=cancel;
  $('#video-convert').onclick=async()=>{
    if(!validate()||encodeController)return;const settings=clip(),plan=exportPlan(settings),controller=new AbortController();encodeController=controller;trimmer.setDisabled(true);importer.setDisabled(true);discardResult();$('#video-controls').disabled=true;$('#video-pick').disabled=true;$('#video-progress-wrap').hidden=false;$('#video-progress').value=0;status('Preparing export…');let videoEncoder;
    try{
      const canvas=document.createElement('canvas'),g=cropGeometry(video.videoWidth,video.videoHeight,settings);canvas.width=g.width;canvas.height=g.height;let gifTools,gif,muxer,target,encodingError,poster,outputTime=0;
      if(settings.format==='gif'){gifTools=await import('./assets/gifenc.js');gif=gifTools.GIFEncoder();}
      else{if(!globalThis.VideoEncoder)throw new Error('MP4 export is unavailable in this browser. Choose GIF or use current Chrome, Edge, or Safari.');const config={codec:'avc1.42001f',width:g.width,height:g.height,bitrate:2_000_000,framerate:settings.fps||Math.max(1,Math.round(1/plan.delay)),avc:{format:'avc'}};const supported=await VideoEncoder.isConfigSupported(config);if(!supported.supported)throw new Error('This browser cannot encode this MP4 size. Choose GIF or a smaller size.');const{Muxer,ArrayBufferTarget}=await import('./assets/mp4-muxer-5.2.2.mjs');target=new ArrayBufferTarget();muxer=new Muxer({target,video:{codec:'avc',width:g.width,height:g.height,frameRate:settings.fps||Math.max(1,Math.round(1/plan.delay))},fastStart:'in-memory'});videoEncoder=new VideoEncoder({output(chunk,meta){try{muxer.addVideoChunk(chunk,meta);}catch(e){encodingError??=e;}},error(e){encodingError??=e;}});videoEncoder.configure(config);}
      for(let i=0;i<plan.times.length;i++){
        if(controller.signal.aborted)throw abortError();if(encodingError)throw encodingError;await seek(video,Math.min(plan.times[i],video.duration-.001),controller.signal);renderVideoFrame(canvas,video,settings);if(!i)poster=canvas.toDataURL('image/jpeg',.85);
        if(gif){const rgba=canvas.getContext('2d').getImageData(0,0,g.width,g.height).data,palette=gifTools.quantize(rgba,256);gif.writeFrame(gifTools.applyPalette(rgba,palette),g.width,g.height,{palette,delay:(plan.delays?.[i]??plan.delay)*1000,repeat:0});}
        else{const timestamp=Math.round(outputTime*1e6),frame=new VideoFrame(canvas,{timestamp,duration:Math.round((outputTime+(plan.delays?.[i]??plan.delay))*1e6)-timestamp});try{videoEncoder.encode(frame,{keyFrame:i%Math.max(1,Math.round(2/plan.delay))===0});}finally{frame.close();}if(videoEncoder.encodeQueueSize>=8)await videoEncoder.flush();}
        outputTime+=plan.delays?.[i]??plan.delay;const percent=Math.round((i+1)/plan.times.length*100);$('#video-progress').value=percent;status(`Creating ${settings.format.toUpperCase()}… ${percent}%`);await new Promise(r=>setTimeout(r,0));
      }
      if(controller.signal.aborted)throw abortError();let blob;if(gif){gif.finish();blob=new Blob([gif.bytes()],{type:'image/gif'});}else{await videoEncoder.flush();if(encodingError)throw encodingError;if(controller.signal.aborted)throw abortError();muxer.finalize();blob=new Blob([target.buffer],{type:'video/mp4'});}if(blob.size>20*1024*1024)throw new Error('Export exceeds 20 MB. Choose a smaller size, lower frame rate, or shorter clip.');
      result={id:'custom-'+crypto.randomUUID(),blob,poster,title:settings.title,caption:[settings.top,settings.bottom].filter(Boolean).join(' / '),width:g.width,height:g.height,duration:plan.duration,sourceUrl:sourceMeta.sourceUrl||'',author:sourceMeta.author||''};resultUrl=URL.createObjectURL(blob);const mp4=settings.format==='mp4';$('#gif-result-image').hidden=mp4;$('#mp4-result-video').hidden=!mp4;$(mp4?'#mp4-result-video':'#gif-result-image').src=resultUrl;$('#video-result-title').textContent=settings.format.toUpperCase()+' preview';$('#video-download').textContent='↓ Download '+settings.format.toUpperCase();$('#gif-result-info').textContent=`${g.width} × ${g.height} · ${plan.duration.toFixed(2)} s · ${(blob.size/1024/1024).toFixed(2)} MB`;$('#gif-result').hidden=false;$('#video-save-note').textContent='';status('Export ready. Preview, download, or save it.');
    }catch(e){status(e.name==='AbortError'?'Export cancelled.':e.message||'Export failed. Try a smaller clip.',e.name!=='AbortError');}
    finally{if(videoEncoder&&videoEncoder.state!=='closed')videoEncoder.close();encodeController=null;importer.setDisabled(false);$('#video-controls').disabled=!ready;$('#video-pick').disabled=false;trimmer.setDisabled(!ready);$('#video-progress-wrap').hidden=true;validate();drawPreview();}
  };
  $('#video-download').onclick=()=>{if(result){downloadBlob(result.blob,'dem-boyz-'+(result.title.toLowerCase().replace(/[^a-z0-9]+/g,'-').slice(0,55)||'video')+(result.blob.type==='video/mp4'?'.mp4':'.gif'));toast('Download started.');}};
  $('#video-save').onclick=async()=>{if(!result)return;const button=$('#video-save'),snapshot=result;button.disabled=true;try{await onSave({...snapshot,title:clip().title,jerry:clip().jerry});if(result===snapshot)$('#video-save-note').textContent='Saved to your library'+(clip().jerry?' and Jerry’s World.':'.');toast('Clip saved.');}catch(e){$('#video-save-note').textContent=e.message||'Could not save. Download to keep a copy.';}finally{button.disabled=false;}};
  $('#video-save-project').onclick=async()=>{if(projectSaving||!ready||!validate())return;projectSaving=true;const b=$('#video-save-project'),version=sourceGeneration;b.disabled=true;try{if(sourceFile.size>20*1024*1024)throw new Error('Projects support source files up to 20 MB. Export this clip, then import the smaller file.');const settings={...clip(),sourceUrl:sourceMeta.sourceUrl||'',author:sourceMeta.author||''};const p=await onSaveProject({id:projectId||undefined,title:settings.title,kind:'video',settings,source:projectId?undefined:sourceFile,poster:preview.toDataURL('image/jpeg',.85)});if(version===sourceGeneration)projectId=p.id;}catch(e){status(e.message,true);}finally{projectSaving=false;validate();}};
  $('#video-save-original').onclick=async()=>{if(!ready||!sourceFile||sourceFile.size>20*1024*1024)return;const b=$('#video-save-original'),version=sourceGeneration;b.disabled=true;try{await saveImportedFile(sourceFile,{...sourceMeta,id:originalId,title:clip().title,jerry:clip().jerry});if(version===sourceGeneration)$('#video-original-note').textContent='Original video saved to your library.';toast('Video saved.');}catch(e){if(version===sourceGeneration)$('#video-original-note').textContent=e.message;}finally{if(version===sourceGeneration)b.disabled=false;}};
  $('#video-download-original').onclick=()=>{if(sourceFile)downloadBlob(sourceFile,sourceFile.name);};
  async function saveImportedFile(file,meta={}){if(file.size>20*1024*1024)throw new Error('Saving videos is limited to 20 MB.');const decoder=document.createElement('video'),url=URL.createObjectURL(file);decoder.muted=true;decoder.playsInline=true;try{const loaded=waitForMedia(decoder,'loadeddata',{signal:meta.signal});decoder.src=url;decoder.load();await loaded;const canvas=document.createElement('canvas');renderVideoFrame(canvas,decoder,{...defaults,edge:640});if(meta.signal?.aborted)throw abortError();await onSave({id:meta.id,blob:file,poster:canvas.toDataURL('image/jpeg',.85),title:meta.title||file.name,caption:meta.caption||'',sourceUrl:meta.sourceUrl||'',author:meta.author||'',width:decoder.videoWidth,height:decoder.videoHeight,jerry:meta.jerry??$('#video-jerry-tag').checked});}finally{decoder.removeAttribute('src');decoder.load();URL.revokeObjectURL(url);}}
  async function loadProject(file,p){const loaded=await loadFile(file,{title:p.title,sourceUrl:p.settings.sourceUrl,author:p.settings.author});if(!loaded)return;projectId=p.id;applySettings(p.settings);trimmer.setRange(p.settings.start,p.settings.end);$('#video-jerry-tag').checked=p.settings.jerry;drawPreview();validate();status('Project restored. Your original and edits are ready.');}
  function reset(){cancel();sourceGeneration++;sourceFile=null;sourceMeta={};projectId=null;ready=false;discardResult();video.destroy?.();video=nativeVideo;trimmer.setSource(video);video.removeAttribute('src');video.load();if(sourceUrl)URL.revokeObjectURL(sourceUrl);sourceUrl=null;$('#video-preview-wrap').hidden=true;$('#video-empty').hidden=false;$('#video-controls').disabled=true;$('#video-title').value='';$('#video-jerry-tag').checked=false;applySettings(defaults);trimmer.setDisabled(true);status('Import a video or animated GIF to start a new project.');}
  return{cancel,loadFile,loadProject,reset,focusImport:()=>importer.focus(),setJerry:value=>{$('#video-jerry-tag').checked=value;}};
}
