// Reviewed selections. See docs/weekly-curation.md.
export const weeklyPicks = [
  {
    "id": "x-2104358074999873726",
    "sourcePostDate": "2026-09-27T23:50:36Z",
    "sourceUrl": "https://x.com/ghetto_gronk/status/2104358074999873726",
    "sourceName": "X",
    "author": "@ghetto_gronk",
    "authorName": "GhettoGronk",
    "title": "America’s team meets Brazil",
    "caption": "Cowboys: “We’re America’s team!”\nLamar Jackson:",
    "originalPostText": "Cowboys: \"We're America's team!\"\n\nLamar Jackson:",
    "type": "video",
    "origin": "community",
    "category": "Game day",
    "subject": "Dallas Cowboys",
    "tags": [
      "Dallas Cowboys",
      "2026 season",
      "Lamar Jackson",
      "Ravens",
      "Brazil",
      "America’s team",
      "after-a-loss",
      "instant-comeback",
      "trash-talk"
    ],
    "momentTags": [
      "after-a-loss",
      "instant-comeback",
      "trash-talk"
    ],
    "qualityScore": 97,
    "originalSrc": "https://video.twimg.com/amplify_video/2104358023648944128/vid/avc1/1920x816/W1iOzK0e5ZWP7YLU.mp4?tag=29",
    "width": 1280,
    "height": 544,
    "duration": 19.477792,
    "sourceDuration": 19.477,
    "sourceExcerpt": null,
    "likesAtReview": 33318,
    "reviewedAt": "2026-09-28",
    "qualityReason": "The Fast Five “This is Brazil” comeback punctures America’s Team bravado immediately after the Rio defeat. A recognizable scene, a very specific current-game setup, strong visual reaction, and over 33,000 likes.",
    "contentNote": "Source date is the current public post; underlying reaction footage can be older.",
    "cleanReview": "Visual review and local automatic speech transcription; no profanity in selected segment.",
    "bestRoast": true,
    "src": "./assets/weekly-picks/x-2104358074999873726.mp4",
    "preview": "./assets/weekly-picks/x-2104358074999873726-poster.jpg",
    "poster": "./assets/weekly-picks/x-2104358074999873726-poster.jpg",
    "curated": true,
    "featuredRank": -200,
    "addedAt": "2026-09-28T17:30:00Z",
    "olderFootage": true
  },
  {
    "id": "x-2104576632371445808",
    "sourcePostDate": "2026-09-28T14:19:04Z",
    "sourceUrl": "https://x.com/FirstTake/status/2104576632371445808",
    "sourceName": "X",
    "author": "@FirstTake",
    "authorName": "First Take",
    "title": "Stephen A. brought the hat",
    "caption": "“I am back from Brazil. … Did you see what happened to those Cowboys?”",
    "originalPostText": "“I am back from Brazil. … Did you see what happened to those Cowboys?” \n\n@stephenasmith is READY to discuss the Dallas Cowboys' loss to the Baltimore Ravens this morning 😭",
    "type": "video",
    "origin": "community",
    "category": "Game day",
    "subject": "Dallas Cowboys",
    "tags": [
      "Dallas Cowboys",
      "2026 season",
      "Stephen A. Smith",
      "First Take",
      "Ravens",
      "Brazil",
      "after-a-loss",
      "victory-lap",
      "group-chat"
    ],
    "momentTags": [
      "after-a-loss",
      "victory-lap",
      "group-chat"
    ],
    "qualityScore": 94,
    "originalSrc": "https://video.twimg.com/amplify_video/2104576556236492800/vid/avc1/1280x720/MtJJouxJfX8QHcu9.mp4?tag=16",
    "width": 1280,
    "height": 720,
    "duration": 14.597917,
    "sourceDuration": 63.158,
    "sourceExcerpt": {
      "start": 15.4,
      "end": 30
    },
    "likesAtReview": 3683,
    "reviewedAt": "2026-09-28",
    "qualityReason": "Fresh Sep 28 First Take footage: Stephen A. in a cowboy hat savors the previous night’s loss. The 15-second excerpt reaches the taunt quickly and preserves his exaggerated reaction.",
    "contentNote": "Source date is the current public post; underlying reaction footage can be older.",
    "cleanReview": "Visual review and local automatic speech transcription; no profanity in selected segment.",
    "bestRoast": true,
    "src": "./assets/weekly-picks/x-2104576632371445808.mp4",
    "preview": "./assets/weekly-picks/x-2104576632371445808-poster.jpg",
    "poster": "./assets/weekly-picks/x-2104576632371445808-poster.jpg",
    "curated": true,
    "featuredRank": -199,
    "addedAt": "2026-09-28T17:30:00Z",
    "olderFootage": false
  },
  {
    "id": "x-2098604071423021202",
    "sourcePostDate": "2026-09-12T02:46:15Z",
    "sourceUrl": "https://x.com/_gridironpod/status/2098604071423021202",
    "sourceName": "X",
    "author": "@_gridironpod",
    "authorName": "Gridiron",
    "title": "Even Skip has had enough",
    "caption": "“I’ve been the most delusional Cowboy fan in the history of Cowboy fans.”",
    "originalPostText": "“I have been the MOST delusional Cowboys Fan in the history of cowboys fans.” 😭 \n\n#nfl #dallascowboys #fans",
    "type": "video",
    "origin": "community",
    "category": "This is our year",
    "subject": "Dallas Cowboys",
    "tags": [
      "Dallas Cowboys",
      "2026 season",
      "Skip Bayless",
      "Delusion",
      "Gridiron",
      "overconfidence",
      "hype-crash",
      "this-is-our-year"
    ],
    "momentTags": [
      "overconfidence",
      "hype-crash",
      "this-is-our-year"
    ],
    "qualityScore": 92,
    "originalSrc": "https://video.twimg.com/amplify_video/2098603961515462656/vid/avc1/720x1280/RwpWIGVJZxpLLttV.mp4?tag=29",
    "width": 720,
    "height": 1280,
    "duration": 12.979633,
    "sourceDuration": 74.608,
    "sourceExcerpt": {
      "start": 0,
      "end": 12.95
    },
    "likesAtReview": 110,
    "reviewedAt": "2026-09-28",
    "qualityReason": "The loudest Dallas believer admits his own delusion, then says he is tired of driving the bandwagon off the cliff. Captioned vertical video; a concise 13-second self-roast. This clean opening avoids profanity later in the full interview.",
    "contentNote": "Source date is the current public post; underlying reaction footage can be older.",
    "cleanReview": "Visual review and local automatic speech transcription; no profanity in selected segment.",
    "bestRoast": true,
    "src": "./assets/weekly-picks/x-2098604071423021202.mp4",
    "preview": "./assets/weekly-picks/x-2098604071423021202-poster.jpg",
    "poster": "./assets/weekly-picks/x-2098604071423021202-poster.jpg",
    "curated": true,
    "featuredRank": -198,
    "addedAt": "2026-09-28T17:30:00Z",
    "olderFootage": true
  },
  {
    "id": "x-2099367337514205585",
    "sourcePostDate": "2026-09-14T05:19:12Z",
    "sourceUrl": "https://x.com/That_Hurts/status/2099367337514205585",
    "sourceName": "X",
    "author": "@That_Hurts",
    "authorName": "That Hurts",
    "title": "No defense left",
    "caption": "Cowboys fans don’t even defend Dak Prescott anymore. They just look at you like this.",
    "originalPostText": "Cowboys fans don’t even defend Dak Prescott anymore they just look at you like this",
    "type": "meme",
    "origin": "community",
    "category": "Game day",
    "subject": "Dallas Cowboys",
    "tags": [
      "Dallas Cowboys",
      "2026 season",
      "Dak Prescott",
      "Fan reaction",
      "Exhausted",
      "speechless",
      "after-a-loss",
      "fan-exhaustion"
    ],
    "momentTags": [
      "speechless",
      "after-a-loss",
      "fan-exhaustion"
    ],
    "qualityScore": 86,
    "originalSrc": "https://pbs.twimg.com/media/HSJzd3GbsAAEmRm.jpg?name=orig",
    "width": 1840,
    "height": 1072,
    "duration": null,
    "sourceDuration": null,
    "sourceExcerpt": null,
    "likesAtReview": 2488,
    "reviewedAt": "2026-09-28",
    "qualityReason": "An expressive, high-resolution movie reaction edited with a Cowboys hat. The exhausted stare directly lands the caption’s joke about fans running out of defenses for Dak; no illegible text or generic team photo.",
    "contentNote": "Source date is the current public post; underlying reaction footage can be older.",
    "cleanReview": "Visual review and local automatic speech transcription; no profanity in selected segment.",
    "bestRoast": true,
    "src": "./assets/weekly-picks/x-2099367337514205585.jpg",
    "preview": "./assets/weekly-picks/x-2099367337514205585.jpg",
    "poster": "./assets/weekly-picks/x-2099367337514205585.jpg",
    "curated": true,
    "featuredRank": -197,
    "addedAt": "2026-09-28T17:30:00Z",
    "olderFootage": true
  },
  {
    "id": "x-2099549510645260442",
    "sourcePostDate": "2026-09-14T17:23:05Z",
    "sourceUrl": "https://x.com/SkattaDart/status/2099549510645260442",
    "sourceName": "X",
    "author": "@SkattaDart",
    "authorName": "SkattaDrt🎯",
    "title": "Don’t run now",
    "caption": "Cowboys fans talked all offseason. Now it’s time to hear about it.",
    "originalPostText": "Nah don’t run cowboys fans you was talking crazy the whole offseason we ain’t forget🤣🤣🤣",
    "type": "video",
    "origin": "community",
    "category": "This is our year",
    "subject": "Dallas Cowboys",
    "tags": [
      "Dallas Cowboys",
      "2026 season",
      "Giants",
      "Fan reaction",
      "Taunting",
      "trash-talk",
      "receipts",
      "after-a-loss"
    ],
    "momentTags": [
      "trash-talk",
      "receipts",
      "after-a-loss"
    ],
    "qualityScore": 84,
    "originalSrc": "https://video.twimg.com/amplify_video/2050758384396468224/vid/avc1/576x564/rq7ilw49s6Pmb00t.mp4?tag=27",
    "width": 576,
    "height": 564,
    "duration": 15.333333,
    "sourceDuration": 26.933,
    "sourceExcerpt": {
      "start": 11.5,
      "end": 26.85
    },
    "likesAtReview": 754,
    "reviewedAt": "2026-09-28",
    "qualityReason": "An animated “I told y’all” taunt followed by a dance fits the post’s receipts-after-a-loss setup. Cropped duration retains the payoff rather than the unrelated Ohio State lead-in. Lower resolution than the other picks but still legible and above 500 pixels both ways.",
    "contentNote": "Source date is the current public post; underlying reaction footage can be older.",
    "cleanReview": "Visual review and local automatic speech transcription; no profanity in selected segment.",
    "bestRoast": true,
    "src": "./assets/weekly-picks/x-2099549510645260442.mp4",
    "preview": "./assets/weekly-picks/x-2099549510645260442-poster.jpg",
    "poster": "./assets/weekly-picks/x-2099549510645260442-poster.jpg",
    "curated": true,
    "featuredRank": -196,
    "addedAt": "2026-09-28T17:30:00Z",
    "olderFootage": true
  }
];
