// Reviewed selections. See docs/weekly-curation.md.
export const weeklyPicks = [
  {
    "id": "reddit-1wsml5e",
    "title": "Garrett would have clapped",
    "caption": "The only difference? Jason Garrett would have clapped after that loss.",
    "subject": "Dallas Cowboys",
    "category": "Game day",
    "tags": [
      "Brian Schottenheimer",
      "Jason Garrett",
      "coaching",
      "same coach",
      "Spider-Man",
      "Peter Parker",
      "clapping",
      "Cowboys"
    ],
    "sourceUrl": "https://www.reddit.com/r/dallascowboys/comments/1wsml5e/the_only_difference_is/",
    "author": "u/keepthatsameenergy1",
    "credit": "Posted by u/keepthatsameenergy1 in r/dallascowboys; original visual creator not independently established",
    "sourcePostDate": "2026-09-28T18:27:11.049Z",
    "classic": false,
    "olderFootage": true,
    "originalSrc": "https://i.redd.it/up2355vi0bsh1.png",
    "width": 700,
    "height": 680,
    "sha256": "55731824ec84291e558e70a2ff452adc50b9b682cff357a9477050d6a6674ded",
    "reviewedAt": "2026-09-29",
    "qualityReason": "Sharp four-panel Peter Parker glasses meme equates Schottenheimer with Garrett. Familiar template makes the replacement-coach/same-result punchline immediate; post caption adds the clap punchline. Specific current Dallas coaching frustration, clean and readable.",
    "contentNote": "Fresh September 28, 2026 post using older film and coach photographs. Satirical coach comparison; not a photo from the current game. Schottenheimer picture is from his Seattle period. Pair image with source-derived caption to preserve the clap punchline.",
    "type": "meme",
    "origin": "community",
    "sourceName": "Reddit",
    "dateVerification": "Canonical Reddit post DOM shreddit-post created-timestamp=2026-09-28T18:27:11.049000+0000; author=keepthatsameenergy1; id=t3_1wsml5e. Browser showed 20h ago on 2026-09-29, consistent with web search Sept28 date.",
    "cleanReview": "Full downloaded 700×680 original inspected; clean, legible faces, no slurs/profanity/politics/sexual or death jokes. No audio.",
    "src": "./assets/weekly-picks/reddit-1wsml5e.png",
    "preview": "./assets/weekly-picks/reddit-1wsml5e.png",
    "momentTags": [
      "after-a-loss",
      "coaching",
      "blame-game"
    ],
    "qualityScore": 92,
    "curated": true,
    "bestRoast": true,
    "featuredRank": -270,
    "addedAt": "2026-09-29T14:11:25.245Z"
  },
  {
    "id": "x-2104358457411310063",
    "sourcePostDate": "2026-09-27T23:52:07Z",
    "sourceUrl": "https://x.com/elijah__116/status/2104358457411310063",
    "sourceName": "X",
    "author": "@elijah__116",
    "authorName": "Elias",
    "title": "Taking out the Dak",
    "caption": "How bout them Cowboys?",
    "type": "meme",
    "origin": "community",
    "category": "Game day",
    "subject": "Dallas Cowboys",
    "tags": [
      "Dallas Cowboys",
      "2026 season",
      "after-a-loss",
      "trash-talk",
      "Dak Prescott",
      "trash can"
    ],
    "momentTags": [
      "after-a-loss",
      "trash-talk",
      "instant-comeback"
    ],
    "qualityScore": 92,
    "originalSrc": "https://pbs.twimg.com/media/HTQu3VjWoAAuj28.jpg?name=orig",
    "width": 1170,
    "height": 989,
    "duration": null,
    "sourceDuration": null,
    "sourceExcerpt": null,
    "likesAtReview": 230,
    "reviewedAt": "2026-09-28",
    "qualityReason": "A simple and harsh visual edit places Dak’s touchdown celebration above a literal trash can. The Cowboys uniform supplies context immediately. Public reply to Timthetatman on Sep 27; distinct from the catalog’s mirror/trash-can illustration.",
    "contentNote": "Public post date verified. Reused edited image; not documentary current-game photography.",
    "cleanReview": "Entire still inspected at readable resolution; no explicit text or gestures.",
    "bestRoast": true,
    "olderFootage": true,
    "sha256": "e377f2d844743d13c4880c4986d7f5f13ee1bbb4d0ba91399c19169b666cd37e",
    "dateVerification": "Canonical post timestamp verified from public source metadata.",
    "curated": true,
    "addedAt": "2026-09-28T20:37:11.162Z",
    "src": "./assets/weekly-picks/x-2104358457411310063.jpg",
    "preview": "./assets/weekly-picks/x-2104358457411310063.jpg",
    "featuredRank": -250,
    "reviewed": true
  },
  {
    "id": "x-2104358457411310063-2",
    "sourcePostDate": "2026-09-27T23:52:07Z",
    "sourceUrl": "https://x.com/elijah__116/status/2104358457411310063",
    "sourceName": "X",
    "author": "@elijah__116",
    "authorName": "Elias",
    "title": "Cowboys fan makeup tutorial",
    "caption": "The Cowboys clown makeup stays on.",
    "type": "meme",
    "origin": "community",
    "category": "Game day",
    "subject": "Dallas Cowboys",
    "tags": [
      "Dallas Cowboys",
      "2026 season",
      "after-a-loss",
      "trash-talk",
      "Timthetatman",
      "clown",
      "makeup"
    ],
    "momentTags": [
      "after-a-loss",
      "trash-talk",
      "instant-comeback"
    ],
    "qualityScore": 92,
    "originalSrc": "https://pbs.twimg.com/media/HTQu3VjX0AAbebK.jpg?name=orig",
    "width": 900,
    "height": 900,
    "duration": null,
    "sourceDuration": null,
    "sourceExcerpt": null,
    "likesAtReview": 230,
    "reviewedAt": "2026-09-28",
    "qualityReason": "Recognizable Timthetatman photo edited with star-branded clown makeup. The joke is carried by the image, not an external explanation; 900px square, clear mobile face, creator watermark retained.",
    "contentNote": "Public post date verified. Reused edited image; not documentary current-game photography.",
    "cleanReview": "Entire still inspected at readable resolution; no explicit text or gestures.",
    "bestRoast": true,
    "olderFootage": true,
    "sha256": "102e44b97a72b2f8b2ad3345432daf80f213044fa8219549e6e8d1894a3312bd",
    "dateVerification": "Canonical post timestamp verified from public source metadata.",
    "curated": true,
    "addedAt": "2026-09-28T20:37:11.163Z",
    "src": "./assets/weekly-picks/x-2104358457411310063-2.jpg",
    "preview": "./assets/weekly-picks/x-2104358457411310063-2.jpg",
    "featuredRank": -249,
    "reviewed": true
  },
  {
    "id": "x-2104357573243929062",
    "sourcePostDate": "2026-09-27T23:48:37Z",
    "sourceUrl": "https://x.com/PrizePicks/status/2104357573243929062",
    "sourceName": "X",
    "author": "@PrizePicks",
    "authorName": "PrizePicks",
    "title": "Still America’s team, though",
    "caption": "“We’re still America’s team though!”",
    "type": "meme",
    "origin": "community",
    "category": "Game day",
    "subject": "Dallas Cowboys",
    "tags": [
      "Dallas Cowboys",
      "2026 season",
      "after-a-loss",
      "trash-talk",
      "Peter Griffin",
      "Family Guy",
      "America’s Team"
    ],
    "momentTags": [
      "after-a-loss",
      "trash-talk",
      "instant-comeback"
    ],
    "qualityScore": 92,
    "originalSrc": "https://pbs.twimg.com/media/HTQt_DJWYAIjbPo.png?name=orig",
    "width": 478,
    "height": 418,
    "duration": null,
    "sourceDuration": null,
    "sourceExcerpt": null,
    "likesAtReview": 207,
    "reviewedAt": "2026-09-28",
    "qualityReason": "Peter Griffin sobs into his knees in a Cowboys cap while protesting America’s Team status. Embedded caption and unmistakable cartoon grief make the joke self-contained. Smaller source, but its single short caption remains readable at phone size.",
    "contentNote": "Public post date verified. Reused edited image; not documentary current-game photography.",
    "cleanReview": "Entire still inspected at readable resolution; no explicit text or gestures.",
    "bestRoast": true,
    "olderFootage": true,
    "sha256": "6aadd99e37378d28fba9f4701e3f21daca79c0d2a21929c03bd08de48d7dfe85",
    "dateVerification": "Canonical post timestamp verified from public source metadata.",
    "curated": true,
    "addedAt": "2026-09-28T20:37:11.163Z",
    "src": "./assets/weekly-picks/x-2104357573243929062.jpg",
    "preview": "./assets/weekly-picks/x-2104357573243929062.jpg",
    "featuredRank": -248,
    "reviewed": true
  },
  {
    "id": "x-2104358181258543426",
    "sourcePostDate": "2026-09-27T23:51:02Z",
    "sourceUrl": "https://x.com/NightcapShow_/status/2104358181258543426",
    "sourceName": "X",
    "author": "@NightcapShow_",
    "authorName": "Nightcap",
    "title": "Roped into another loss",
    "caption": "The Ravens tie up Iso Joe and his Cowboys in Brazil.",
    "type": "meme",
    "origin": "community",
    "category": "Game day",
    "subject": "Dallas Cowboys",
    "tags": [
      "Dallas Cowboys",
      "2026 season",
      "after-a-loss",
      "trash-talk",
      "Shannon Sharpe",
      "Joe Johnson",
      "Ravens",
      "Nightcap",
      "Brazil"
    ],
    "momentTags": [
      "after-a-loss",
      "trash-talk",
      "instant-comeback"
    ],
    "qualityScore": 92,
    "originalSrc": "https://pbs.twimg.com/media/HTQunIWbAAATovA.jpg?name=orig",
    "width": 1668,
    "height": 2048,
    "duration": null,
    "sourceDuration": null,
    "sourceExcerpt": null,
    "likesAtReview": 2147,
    "reviewedAt": "2026-09-28",
    "qualityReason": "Official Nightcap roast after the Rio loss: Shannon Sharpe as a Ravens cowboy lassos a flailing Joe Johnson in a Dallas jersey. Exaggerated, clearly fictional collage with large RAVENS WIN lettering. Original Nightcap watermark and credit retained.",
    "contentNote": "Public post date verified. Creator’s cartoon satire; not a documentary image.",
    "cleanReview": "Entire still inspected at readable resolution; no explicit text or gestures.",
    "bestRoast": true,
    "olderFootage": false,
    "sha256": "7496ebbd28933781a7008215bb20d778153b656e71c9413dd5e8bef5f4f6e4b5",
    "dateVerification": "Canonical post timestamp verified from public source metadata.",
    "curated": true,
    "addedAt": "2026-09-28T20:37:11.163Z",
    "src": "./assets/weekly-picks/x-2104358181258543426.jpg",
    "preview": "./assets/weekly-picks/x-2104358181258543426.jpg",
    "featuredRank": -247,
    "reviewed": true
  },
  {
    "id": "x-2103094596108513751",
    "sourcePostDate": "2026-09-24T12:09:59Z",
    "sourceUrl": "https://x.com/500coaches/status/2103094596108513751",
    "sourceName": "X",
    "author": "@500coaches",
    "authorName": "500 Coaches | Cowboys Misery Department",
    "title": "The run-defense playbook",
    "caption": "Run defense: HOPE. PRAYER.",
    "type": "meme",
    "origin": "community",
    "category": "Game day",
    "subject": "Dallas Cowboys",
    "tags": [
      "Dallas Cowboys",
      "2026 season",
      "Ravens",
      "Derrick Henry",
      "Lamar Jackson",
      "run defense",
      "hope",
      "prayer",
      "pregame"
    ],
    "momentTags": [
      "trash-talk",
      "this-is-our-year"
    ],
    "qualityScore": 92,
    "originalSrc": "https://pbs.twimg.com/media/HS-xY7BXUAAgjfz.jpg?name=orig",
    "width": 1145,
    "height": 1374,
    "duration": null,
    "sourceDuration": null,
    "sourceExcerpt": null,
    "likesAtReview": 0,
    "reviewedAt": "2026-09-28",
    "qualityReason": "Original @500coaches cartoon: Dallas defenders look for answers in a playbook containing only HOPE and PRAYER as Derrick Henry and Lamar Jackson run past. Specific current matchup, readable punchline, full creator credit.",
    "contentNote": "Public post date verified. Creator’s cartoon satire; not a documentary image.",
    "cleanReview": "Entire still inspected at readable resolution; no explicit text or gestures.",
    "bestRoast": true,
    "olderFootage": false,
    "sha256": "1bd867da7e9ff26bbc733f5fa57b00fe65e305a0f4f201e480b96decbc3977c0",
    "dateVerification": "Canonical post timestamp verified from public source metadata.",
    "curated": true,
    "addedAt": "2026-09-28T20:37:11.163Z",
    "src": "./assets/weekly-picks/x-2103094596108513751.jpg",
    "preview": "./assets/weekly-picks/x-2103094596108513751.jpg",
    "featuredRank": -260,
    "reviewed": true
  },
  {
    "id": "x-2104371066646716493",
    "sourcePostDate": "2026-09-28T00:42:14Z",
    "sourceUrl": "https://x.com/500coaches/status/2104371066646716493",
    "sourceName": "X",
    "author": "@500coaches",
    "authorName": "500 Coaches | Cowboys Misery Department",
    "title": "No participation pens",
    "caption": "One win. One pen.",
    "type": "meme",
    "origin": "community",
    "category": "Game day",
    "subject": "Dallas Cowboys",
    "tags": [
      "Dallas Cowboys",
      "2026 season",
      "after-a-loss",
      "trash-talk",
      "Brian Schottenheimer",
      "visor",
      "one win",
      "one pen"
    ],
    "momentTags": [
      "after-a-loss",
      "trash-talk",
      "instant-comeback"
    ],
    "qualityScore": 92,
    "originalSrc": "https://pbs.twimg.com/media/HTQ6Uq7WUAEhdZ-.jpg?name=orig",
    "width": 1254,
    "height": 1254,
    "duration": null,
    "sourceDuration": null,
    "sourceExcerpt": null,
    "likesAtReview": 0,
    "reviewedAt": "2026-09-28",
    "qualityReason": "Fresh post-loss @500coaches gag ties the coach’s visor pen to Dallas’s single win, with the 34–31 Ravens result embedded. Distinct joke from the existing excessive-pen visor image; concise, legible, Cowboys-branded.",
    "contentNote": "Public post date verified. Creator’s cartoon satire; not a documentary image.",
    "cleanReview": "Entire still inspected at readable resolution; no explicit text or gestures.",
    "bestRoast": true,
    "olderFootage": false,
    "sha256": "d1182a6e179f4c84d5d9eb4999ec689570249d8862749244d97ad4430780488c",
    "dateVerification": "Canonical post timestamp verified from public source metadata.",
    "curated": true,
    "addedAt": "2026-09-28T20:37:11.163Z",
    "src": "./assets/weekly-picks/x-2104371066646716493.jpg",
    "preview": "./assets/weekly-picks/x-2104371066646716493.jpg",
    "featuredRank": -259,
    "reviewed": true
  },
  {
    "id": "x-2104359141527658576",
    "sourcePostDate": "2026-09-27T23:54:51Z",
    "sourceUrl": "https://x.com/stephenasmith/status/2104359141527658576",
    "sourceName": "X",
    "author": "@stephenasmith",
    "authorName": "Stephen A Smith",
    "title": "Stephen A. tries not to laugh",
    "caption": "Stephen A. after the Cowboys lose in Brazil: “I couldn’t. I just couldn’t.”",
    "type": "gif",
    "origin": "community",
    "category": "Game day",
    "subject": "Dallas Cowboys",
    "tags": [
      "Dallas Cowboys",
      "2026 season",
      "Stephen A. Smith",
      "Ravens",
      "Brazil",
      "after-a-loss",
      "victory-lap"
    ],
    "momentTags": [
      "after-a-loss",
      "victory-lap",
      "instant-comeback"
    ],
    "qualityScore": 94,
    "originalSrc": "https://video.twimg.com/amplify_video/2104359107486453760/vid/avc1/720x1280/-8vGEjsDMQm2kw9B.mp4?tag=29",
    "width": 320,
    "height": 568,
    "duration": 5.01,
    "sourceDuration": 16.136,
    "sourceExcerpt": {
      "start": 4,
      "end": 9
    },
    "likesAtReview": 48937,
    "reviewedAt": "2026-09-28",
    "qualityReason": "Original Stephen A. post from the Rio stadium after the loss. A five-second loop of him trying to suppress his laughter is instantly useful in a group chat. This is new stadium footage, different from the catalog’s next-morning First Take hat excerpt.",
    "contentNote": "Silent GIF excerpt of the creator’s original current-game video; caption comes from the public post, not asserted dialogue.",
    "cleanReview": "Visual review of source frames throughout selected 4–9 seconds; exported GIF contains no audio and no explicit text or gestures.",
    "bestRoast": true,
    "olderFootage": false,
    "sha256": "f6a84d742bc443a17ce8f9740ded4fdcc3e234765305ce989cac3deef9a91c99",
    "dateVerification": "Canonical post timestamp verified from public source metadata.",
    "curated": true,
    "addedAt": "2026-09-28T20:37:11.163Z",
    "src": "./assets/weekly-picks/x-2104359141527658576.gif",
    "preview": "./assets/weekly-picks/x-2104359141527658576-poster.jpg",
    "poster": "./assets/weekly-picks/x-2104359141527658576-poster.jpg",
    "featuredRank": -244,
    "reviewed": true
  },
  {
    "id": "x-2104359161144229956",
    "sourcePostDate": "2026-09-27T23:54:55Z",
    "sourceUrl": "https://x.com/ghetto_gronk/status/2104359161144229956",
    "sourceName": "X",
    "author": "@ghetto_gronk",
    "authorName": "GhettoGronk",
    "title": "Seven seconds. Kindergarten defense.",
    "caption": "The Cowboys defense with 7 seconds left",
    "originalPostText": "The Cowboys defense with 7 seconds left",
    "type": "video",
    "origin": "community",
    "category": "Game day",
    "subject": "Dallas Cowboys",
    "tags": [
      "Dallas Cowboys",
      "2026 season",
      "Ravens",
      "Brazil",
      "Blown lead",
      "SpongeBob",
      "Patrick",
      "after-a-loss",
      "seven seconds"
    ],
    "momentTags": [
      "after-a-loss",
      "blown-lead",
      "instant-comeback",
      "trash-talk"
    ],
    "qualityScore": 96,
    "originalSrc": "https://video.twimg.com/amplify_video/2104359086892462080/vid/avc1/1920x1080/4SsJRtZErtsi-qWB.mp4?tag=29",
    "width": 1280,
    "height": 720,
    "duration": 6.570667,
    "sourceDuration": 6.52,
    "sourceExcerpt": null,
    "likesAtReview": 3191,
    "reviewedAt": "2026-09-28",
    "qualityReason": "Six-second cartoon punchline: Patrick and SpongeBob play with toddler toys while Dallas needed one competent defensive stop. Clear, absurd, immediately readable, and tied to the final seven seconds in Rio. Direct original creator attribution verified from repost media facet, then original FxTwitter response.",
    "contentNote": "Posted after the Sep 27 Rio game; reused SpongeBob cartoon footage. Keep the source caption visible alongside the clip.",
    "cleanReview": "Reviewed contact sheet covering every second of the 6.5-second clip. Local faster-whisper base.en transcribed only repeated nonverbal \"Lumba\" cartoon noises; no profanity detected.",
    "bestRoast": true,
    "olderFootage": true,
    "sha256": "6c510740e6cb010f1e2d3ed1ac375832a4fbfd96f8d0f101f8aa44449ca31b3b",
    "src": "./assets/weekly-picks/x-2104359161144229956.mp4",
    "poster": "./assets/weekly-picks/x-2104359161144229956-poster.jpg",
    "preview": "./assets/weekly-picks/x-2104359161144229956-poster.jpg",
    "curated": true,
    "featuredRank": -220,
    "addedAt": "2026-09-28T18:44:17.164Z"
  },
  {
    "id": "x-2104368000304640275",
    "sourcePostDate": "2026-09-28T00:30:03.000Z",
    "sourceUrl": "https://x.com/NFLMemes/status/2104368000304640275",
    "sourceName": "X",
    "author": "@NFLMemes",
    "authorName": "NFL Memes",
    "title": "The whole stadium took a victory lap",
    "caption": "80,000 people yelling “SIUUU!” in unison after the Cowboys choke in embarrassing fashion might legitimately be a top-5 moment in NFL history",
    "type": "video",
    "origin": "community",
    "category": "Game day",
    "subject": "Dallas Cowboys",
    "tags": [
      "Dallas Cowboys",
      "2026 season",
      "Ravens",
      "Brazil",
      "SIUU",
      "Tyler Loop",
      "Lamar Jackson",
      "choke",
      "after-a-loss",
      "victory-lap",
      "trash-talk"
    ],
    "momentTags": [
      "after-a-loss",
      "victory-lap",
      "trash-talk"
    ],
    "originalSrc": "https://video.twimg.com/amplify_video/2104367686188662784/vid/avc1/1920x1080/hktv6Qq4qfVk0C5j.mp4?tag=29",
    "width": 1280,
    "height": 720,
    "duration": 10.901333,
    "sourceDuration": 10.842,
    "sourceExcerpt": null,
    "likesAtReview": 50496,
    "reviewedAt": "2026-09-28",
    "qualityReason": "The winning kick is followed by the Ravens’ synchronized SIUU celebration: a short, exuberant victory lap after Dallas’s last-second collapse. The original NFL Memes caption supplies the taunt.",
    "contentNote": "Current game footage from the Sep 27 Rio game. The stadium-count claim is the source creator’s caption.",
    "cleanReview": "Contact-sheet review across the complete clip and local automatic speech transcription: broadcast commentary and crowd audio, no profanity detected.",
    "bestRoast": true,
    "olderFootage": false,
    "curated": true,
    "featuredRank": -218,
    "addedAt": "2026-09-28T18:44:17.164Z",
    "src": "./assets/weekly-picks/x-2104368000304640275.mp4",
    "poster": "./assets/weekly-picks/x-2104368000304640275-poster.jpg",
    "preview": "./assets/weekly-picks/x-2104368000304640275-poster.jpg"
  },
  {
    "id": "x-2104358074999873726",
    "sourcePostDate": "2026-09-27T23:50:36Z",
    "sourceUrl": "https://x.com/ghetto_gronk/status/2104358074999873726",
    "sourceName": "X",
    "author": "@ghetto_gronk",
    "authorName": "GhettoGronk",
    "title": "America’s team meets Brazil",
    "caption": "Cowboys: “We’re America’s team!”\nLamar Jackson:",
    "originalPostText": "Cowboys: \"We're America's team!\"\n\nLamar Jackson:",
    "type": "video",
    "origin": "community",
    "category": "Game day",
    "subject": "Dallas Cowboys",
    "tags": [
      "Dallas Cowboys",
      "2026 season",
      "Lamar Jackson",
      "Ravens",
      "Brazil",
      "America’s team",
      "after-a-loss",
      "instant-comeback",
      "trash-talk"
    ],
    "momentTags": [
      "after-a-loss",
      "instant-comeback",
      "trash-talk"
    ],
    "qualityScore": 97,
    "originalSrc": "https://video.twimg.com/amplify_video/2104358023648944128/vid/avc1/1920x816/W1iOzK0e5ZWP7YLU.mp4?tag=29",
    "width": 1280,
    "height": 544,
    "duration": 19.477792,
    "sourceDuration": 19.477,
    "sourceExcerpt": null,
    "likesAtReview": 33318,
    "reviewedAt": "2026-09-28",
    "qualityReason": "The Fast Five “This is Brazil” comeback punctures America’s Team bravado immediately after the Rio defeat. A recognizable scene, a very specific current-game setup, strong visual reaction, and over 33,000 likes.",
    "contentNote": "Source date is the current public post; underlying reaction footage can be older.",
    "cleanReview": "Visual review and local automatic speech transcription; no profanity in selected segment.",
    "bestRoast": true,
    "src": "./assets/weekly-picks/x-2104358074999873726.mp4",
    "preview": "./assets/weekly-picks/x-2104358074999873726-poster.jpg",
    "poster": "./assets/weekly-picks/x-2104358074999873726-poster.jpg",
    "curated": true,
    "featuredRank": -200,
    "addedAt": "2026-09-28T17:30:00Z",
    "olderFootage": true
  },
  {
    "id": "x-2104576632371445808",
    "sourcePostDate": "2026-09-28T14:19:04Z",
    "sourceUrl": "https://x.com/FirstTake/status/2104576632371445808",
    "sourceName": "X",
    "author": "@FirstTake",
    "authorName": "First Take",
    "title": "Stephen A. brought the hat",
    "caption": "“I am back from Brazil. … Did you see what happened to those Cowboys?”",
    "originalPostText": "“I am back from Brazil. … Did you see what happened to those Cowboys?” \n\n@stephenasmith is READY to discuss the Dallas Cowboys' loss to the Baltimore Ravens this morning 😭",
    "type": "video",
    "origin": "community",
    "category": "Game day",
    "subject": "Dallas Cowboys",
    "tags": [
      "Dallas Cowboys",
      "2026 season",
      "Stephen A. Smith",
      "First Take",
      "Ravens",
      "Brazil",
      "after-a-loss",
      "victory-lap",
      "group-chat"
    ],
    "momentTags": [
      "after-a-loss",
      "victory-lap",
      "group-chat"
    ],
    "qualityScore": 94,
    "originalSrc": "https://video.twimg.com/amplify_video/2104576556236492800/vid/avc1/1280x720/MtJJouxJfX8QHcu9.mp4?tag=16",
    "width": 1280,
    "height": 720,
    "duration": 14.597917,
    "sourceDuration": 63.158,
    "sourceExcerpt": {
      "start": 15.4,
      "end": 30
    },
    "likesAtReview": 3683,
    "reviewedAt": "2026-09-28",
    "qualityReason": "Fresh Sep 28 First Take footage: Stephen A. in a cowboy hat savors the previous night’s loss. The 15-second excerpt reaches the taunt quickly and preserves his exaggerated reaction.",
    "contentNote": "Source date is the current public post; underlying reaction footage can be older.",
    "cleanReview": "Visual review and local automatic speech transcription; no profanity in selected segment.",
    "bestRoast": true,
    "src": "./assets/weekly-picks/x-2104576632371445808.mp4",
    "preview": "./assets/weekly-picks/x-2104576632371445808-poster.jpg",
    "poster": "./assets/weekly-picks/x-2104576632371445808-poster.jpg",
    "curated": true,
    "featuredRank": -199,
    "addedAt": "2026-09-28T17:30:00Z",
    "olderFootage": false
  },
  {
    "id": "x-2098604071423021202",
    "sourcePostDate": "2026-09-12T02:46:15Z",
    "sourceUrl": "https://x.com/_gridironpod/status/2098604071423021202",
    "sourceName": "X",
    "author": "@_gridironpod",
    "authorName": "Gridiron",
    "title": "Even Skip has had enough",
    "caption": "“I’ve been the most delusional Cowboy fan in the history of Cowboy fans.”",
    "originalPostText": "“I have been the MOST delusional Cowboys Fan in the history of cowboys fans.” 😭 \n\n#nfl #dallascowboys #fans",
    "type": "video",
    "origin": "community",
    "category": "This is our year",
    "subject": "Dallas Cowboys",
    "tags": [
      "Dallas Cowboys",
      "2026 season",
      "Skip Bayless",
      "Delusion",
      "Gridiron",
      "overconfidence",
      "hype-crash",
      "this-is-our-year"
    ],
    "momentTags": [
      "overconfidence",
      "hype-crash",
      "this-is-our-year"
    ],
    "qualityScore": 92,
    "originalSrc": "https://video.twimg.com/amplify_video/2098603961515462656/vid/avc1/720x1280/RwpWIGVJZxpLLttV.mp4?tag=29",
    "width": 720,
    "height": 1280,
    "duration": 12.979633,
    "sourceDuration": 74.608,
    "sourceExcerpt": {
      "start": 0,
      "end": 12.95
    },
    "likesAtReview": 110,
    "reviewedAt": "2026-09-28",
    "qualityReason": "The loudest Dallas believer admits his own delusion, then says he is tired of driving the bandwagon off the cliff. Captioned vertical video; a concise 13-second self-roast. This clean opening avoids profanity later in the full interview.",
    "contentNote": "Source date is the current public post; underlying reaction footage can be older.",
    "cleanReview": "Visual review and local automatic speech transcription; no profanity in selected segment.",
    "bestRoast": true,
    "src": "./assets/weekly-picks/x-2098604071423021202.mp4",
    "preview": "./assets/weekly-picks/x-2098604071423021202-poster.jpg",
    "poster": "./assets/weekly-picks/x-2098604071423021202-poster.jpg",
    "curated": true,
    "featuredRank": -198,
    "addedAt": "2026-09-28T17:30:00Z",
    "olderFootage": true
  },
  {
    "id": "x-2099367337514205585",
    "sourcePostDate": "2026-09-14T05:19:12Z",
    "sourceUrl": "https://x.com/That_Hurts/status/2099367337514205585",
    "sourceName": "X",
    "author": "@That_Hurts",
    "authorName": "That Hurts",
    "title": "No defense left",
    "caption": "Cowboys fans don’t even defend Dak Prescott anymore. They just look at you like this.",
    "originalPostText": "Cowboys fans don’t even defend Dak Prescott anymore they just look at you like this",
    "type": "meme",
    "origin": "community",
    "category": "Game day",
    "subject": "Dallas Cowboys",
    "tags": [
      "Dallas Cowboys",
      "2026 season",
      "Dak Prescott",
      "Fan reaction",
      "Exhausted",
      "speechless",
      "after-a-loss",
      "fan-exhaustion"
    ],
    "momentTags": [
      "speechless",
      "after-a-loss",
      "fan-exhaustion"
    ],
    "qualityScore": 86,
    "originalSrc": "https://pbs.twimg.com/media/HSJzd3GbsAAEmRm.jpg?name=orig",
    "width": 1840,
    "height": 1072,
    "duration": null,
    "sourceDuration": null,
    "sourceExcerpt": null,
    "likesAtReview": 2488,
    "reviewedAt": "2026-09-28",
    "qualityReason": "An expressive, high-resolution movie reaction edited with a Cowboys hat. The exhausted stare directly lands the caption’s joke about fans running out of defenses for Dak; no illegible text or generic team photo.",
    "contentNote": "Source date is the current public post; underlying reaction footage can be older.",
    "cleanReview": "Visual review and local automatic speech transcription; no profanity in selected segment.",
    "bestRoast": true,
    "src": "./assets/weekly-picks/x-2099367337514205585.jpg",
    "preview": "./assets/weekly-picks/x-2099367337514205585.jpg",
    "poster": "./assets/weekly-picks/x-2099367337514205585.jpg",
    "curated": true,
    "featuredRank": -197,
    "addedAt": "2026-09-28T17:30:00Z",
    "olderFootage": true
  },
  {
    "id": "x-2099549510645260442",
    "sourcePostDate": "2026-09-14T17:23:05Z",
    "sourceUrl": "https://x.com/SkattaDart/status/2099549510645260442",
    "sourceName": "X",
    "author": "@SkattaDart",
    "authorName": "SkattaDrt🎯",
    "title": "Don’t run now",
    "caption": "Cowboys fans talked all offseason. Now it’s time to hear about it.",
    "originalPostText": "Nah don’t run cowboys fans you was talking crazy the whole offseason we ain’t forget🤣🤣🤣",
    "type": "video",
    "origin": "community",
    "category": "This is our year",
    "subject": "Dallas Cowboys",
    "tags": [
      "Dallas Cowboys",
      "2026 season",
      "Giants",
      "Fan reaction",
      "Taunting",
      "trash-talk",
      "receipts",
      "after-a-loss"
    ],
    "momentTags": [
      "trash-talk",
      "receipts",
      "after-a-loss"
    ],
    "qualityScore": 84,
    "originalSrc": "https://video.twimg.com/amplify_video/2050758384396468224/vid/avc1/576x564/rq7ilw49s6Pmb00t.mp4?tag=27",
    "width": 576,
    "height": 564,
    "duration": 15.333333,
    "sourceDuration": 26.933,
    "sourceExcerpt": {
      "start": 11.5,
      "end": 26.85
    },
    "likesAtReview": 754,
    "reviewedAt": "2026-09-28",
    "qualityReason": "An animated “I told y’all” taunt followed by a dance fits the post’s receipts-after-a-loss setup. Cropped duration retains the payoff rather than the unrelated Ohio State lead-in. Lower resolution than the other picks but still legible and above 500 pixels both ways.",
    "contentNote": "Source date is the current public post; underlying reaction footage can be older.",
    "cleanReview": "Visual review and local automatic speech transcription; no profanity in selected segment.",
    "bestRoast": true,
    "src": "./assets/weekly-picks/x-2099549510645260442.mp4",
    "preview": "./assets/weekly-picks/x-2099549510645260442-poster.jpg",
    "poster": "./assets/weekly-picks/x-2099549510645260442-poster.jpg",
    "curated": true,
    "featuredRank": -196,
    "addedAt": "2026-09-28T17:30:00Z",
    "olderFootage": true
  }
];
