const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function createWorkspaceUI(root, options) {
  const {state,api,toast,refresh,onBrowse,onOpenProject,onFavorite,onRemove}=options;
  const dialog=document.createElement('dialog');dialog.className='workspace-dialog';document.body.append(dialog);
  let mode='',busy=false,review=[],reviewIndex=0,history=[],archived=false;
  const $=s=>root.querySelector(s);
  function close(){if(busy)return;dialog.querySelector('video')?.pause();dialog.close();}
  dialog.addEventListener('click',e=>{if(e.target===dialog)close();if(e.target.closest('[data-workspace-close]'))close();});
  dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});
  dialog.addEventListener('close',()=>dialog.querySelector('video')?.pause());
  async function action(run){if(busy)return false;busy=true;dialog.querySelectorAll('button').forEach(b=>b.disabled=true);try{await run();return true;}catch(e){toast(e.message||'Could not save. Try again.');return false;}finally{busy=false;dialog.querySelectorAll('button').forEach(b=>b.disabled=false);}}
  async function createFolder(name){const folder=await api('/api/collections',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:'folder-'+crypto.randomUUID(),name})});await refresh();return folder;}
  function render(next=mode){mode=next;const s=state();if(mode==='collections'){
    root.innerHTML=`<div class="maker-header"><div><span class="eyebrow">YOUR LIBRARY</span><h1>COLLECTIONS</h1><p>Organize memes and clips into folders saved in this browser.</p></div><button class="back-link" data-view="library">← Back to library</button></div><form id="collection-create" class="workspace-create"><label>Collection name<input id="collection-name" maxlength="60" required placeholder="Jerry meltdowns"></label><button class="button primary">Create collection</button></form><div class="workspace-list">${s.collections.length?s.collections.map(f=>`<article class="workspace-tile"><span class="eyebrow">${s.memberships.filter(m=>m.collectionId===f.id&&!s.removed.has(m.itemId)).length} SAVED</span><h2>${esc(f.name)}</h2><div class="export-actions"><button class="button primary" data-folder-browse="${f.id}">Open collection</button><button class="button outline" data-folder-rename="${f.id}">Rename</button><button class="button ghost" data-folder-remove="${f.id}">Remove folder</button></div></article>`).join(''):'<div class="empty"><h3>No collections yet.</h3><p>Create a folder above, then use Add to collection on any meme or clip.</p></div>'}</div>`;
    $('#collection-create').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{await createFolder($('#collection-name').value.trim());render();toast('Collection created.');}catch(e){toast(e.message);}finally{button.disabled=false;}};
  }else{
    const projects=s.projects.filter(p=>p.archived===archived);
    root.innerHTML=`<div class="maker-header"><div><span class="eyebrow">EDITABLE ORIGINALS</span><h1>PROJECTS</h1><p>Reopen your source media, captions, trim, and effects. Project sources up to 20 MB.</p></div><button class="back-link" data-view="library">← Back to library</button></div><div class="project-toolbar"><button class="button ${archived?'outline':'primary'}" data-project-list="active">Active projects</button><button class="button ${archived?'primary':'outline'}" data-project-list="archived">Archived projects</button><button class="button outline" data-new-project="image">New image project</button><button class="button outline" data-new-project="video">New video project</button></div><div class="workspace-list">${projects.length?projects.map(p=>`<article class="workspace-tile project-tile">${p.poster?`<img src="${esc(p.poster)}" alt="${esc(p.title)}" loading="lazy">`:''}<span class="eyebrow">${p.kind==='video'?'VIDEO':'IMAGE'} PROJECT</span><h2>${esc(p.title)}</h2><p>Saved ${new Date(p.updatedAt).toLocaleDateString()}</p><div class="export-actions">${!archived?`<button class="button primary" data-project-open="${p.id}">Resume editing</button>`:''}<button class="button outline" data-project-archive="${p.id}" data-archived="${!archived}">${archived?'Restore':'Archive'}</button></div></article>`).join(''):`<div class="empty"><h3>No ${archived?'archived':'saved'} projects.</h3><p>Use Save project in either editor to keep your original and editing settings.</p></div>`}</div>`;
  }}
  root.addEventListener('click',async e=>{
    const b=e.target.closest('button');if(!b)return;
    if(b.dataset.folderBrowse)onBrowse(b.dataset.folderBrowse);
    if(b.dataset.projectList){archived=b.dataset.projectList==='archived';render('projects');}
    if(b.dataset.projectOpen){b.disabled=true;try{await onOpenProject(b.dataset.projectOpen);}catch(e){toast(e.message);}finally{b.disabled=false;}}
    if(b.dataset.projectArchive){b.disabled=true;try{await api('/api/projects/'+b.dataset.projectArchive,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({archived:b.dataset.archived==='true'})});await refresh();render();}catch(e){toast(e.message);b.disabled=false;}}
    if(b.dataset.folderRename){dialog.classList.remove('review-dialog');const f=state().collections.find(f=>f.id===b.dataset.folderRename);dialog.innerHTML=`<button class="dialog-close" data-workspace-close aria-label="Close collection dialog">×</button><h2>Rename collection</h2><form id="rename-folder"><label>Name<input id="rename-name" value="${esc(f.name)}" maxlength="60" required></label><button class="button primary">Save name</button></form>`;dialog.showModal();dialog.querySelector('form').onsubmit=async event=>{event.preventDefault();if(await action(async()=>{await api('/api/collections/'+f.id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:dialog.querySelector('input').value.trim()})});await refresh();render();}))close();};}
    if(b.dataset.folderRemove){const id=b.dataset.folderRemove;b.disabled=true;try{await api('/api/collections/'+id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({archived:true})});await refresh();render();toast('Folder removed. Its media stays in your library.',async()=>{try{await api('/api/collections/'+id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({archived:false})});await refresh();render();}catch(e){toast(e.message);}});}catch(e){toast(e.message);b.disabled=false;}}
  });
  function openMemberships(item){
    const s=state();dialog.innerHTML=`<button class="dialog-close" data-workspace-close aria-label="Close collections">×</button><h2>Add to collection</h2><p>${esc(item.title)}</p><div class="folder-checks">${s.collections.map(f=>`<label class="check-label"><input type="checkbox" data-folder="${f.id}" ${s.memberships.some(m=>m.collectionId===f.id&&m.itemId===item.id)?'checked':''}>${esc(f.name)}</label>`).join('')||'<p>Create your first collection below.</p>'}</div><form id="quick-folder"><label>New collection<input id="quick-folder-name" maxlength="60" required placeholder="Group chat favorites"></label><button class="button outline">Create and add</button></form>`;
    if(!dialog.open)dialog.showModal();
    dialog.querySelectorAll('[data-folder]').forEach(input=>input.onchange=async()=>{const included=input.checked;input.disabled=true;try{await api('/api/collections/'+input.dataset.folder+'/items',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({itemId:item.id,included})});await refresh();toast(included?'Added to collection.':'Removed from collection.');}catch(e){input.checked=!included;toast(e.message);}finally{input.disabled=false;}});
    dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();const name=dialog.querySelector('#quick-folder-name').value.trim();await action(async()=>{const f=await createFolder(name);await api('/api/collections/'+f.id+'/items',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({itemId:item.id,included:true})});await refresh();openMemberships(item);toast('Collection created and item added.');});};
  }
  function renderReview(){
    dialog.querySelector('video')?.pause();const m=review[reviewIndex];
    dialog.innerHTML=`<button class="dialog-close" data-workspace-close aria-label="Close review">×</button><div class="review-heading"><span class="eyebrow">KEEP / TRASH</span><span>${Math.min(reviewIndex+1,review.length)} / ${review.length}</span></div>${m?`<h2>${esc(m.title)}</h2><div class="review-media">${m.type==='video'?`<video src="${esc(m.src)}" poster="${esc(m.poster||m.preview)}" controls playsinline></video>`:`<img src="${esc(m.src)}" alt="${esc(m.title)}">`}${m.top?`<span class="caption top">${esc(m.top)}</span><span class="caption bottom">${esc(m.bottom)}</span>`:''}</div><p>${esc(m.caption||'')}</p><div class="review-actions"><button class="button outline" data-review="trash">← Remove</button><button class="button primary" data-review="keep">Keep →</button><button class="button outline" data-review="skip">Skip ↓</button></div>`:`<div class="empty"><h2>Review complete.</h2><p>${history.filter(h=>h.action==='keep').length} kept · ${history.filter(h=>h.action==='trash').length} removed · ${history.filter(h=>h.action==='skip').length} skipped</p><button class="button primary" data-workspace-close>Back to library</button></div>`}<div class="review-footer"><button class="button ghost" data-review="undo" ${!history.length?'disabled':''}>Undo last</button><span>Keep saves to favorites. Removed items can be restored.</span></div>`;
  }
  async function reviewAction(which){if(busy)return;const m=review[reviewIndex];if(which==='undo'){
    const h=history.at(-1);if(!h)return;const success=await action(async()=>{if(h.action==='keep'&&!await onFavorite(h.item.id,h.wasFavorite))throw Error('Favorite could not be restored.');if(h.action==='trash'&&!await onRemove(h.item.id,false))throw Error('Item could not be restored.');});if(success){history.pop();reviewIndex--;renderReview();}return;
  }if(!m)return;
    const wasFavorite=state().favorites.includes(m.id);const success=await action(async()=>{if(which==='keep'&&!await onFavorite(m.id,true))throw Error('Favorite could not be saved.');if(which==='trash'&&!await onRemove(m.id,true))throw Error('Item could not be removed.');});if(success){history.push({item:m,action:which,wasFavorite});reviewIndex++;renderReview();}
  }
  dialog.addEventListener('click',e=>{const b=e.target.closest('[data-review]');if(b)reviewAction(b.dataset.review);});
  dialog.addEventListener('keydown',e=>{if(!dialog.classList.contains('review-dialog')||['INPUT','TEXTAREA','VIDEO'].includes(e.target.tagName))return;const key={ArrowLeft:'trash',ArrowRight:'keep',ArrowDown:'skip',Backspace:'undo'}[e.key];if(key){e.preventDefault();reviewAction(key);}});
  return {render,openMemberships(item){dialog.classList.remove('review-dialog');openMemberships(item);},openReview(items){review=items.filter(m=>m.type!=='template');if(!review.length){toast('No items to review with these filters.');return;}reviewIndex=0;history=[];dialog.classList.add('review-dialog');renderReview();dialog.showModal();}};
}
